# coding: utf-8

"""
    NativeBPM Engine REST API

    REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nativebpm_client.models.workflow_ast import WorkflowAST

class TestWorkflowAST(unittest.TestCase):
    """WorkflowAST unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowAST:
        """Test WorkflowAST
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowAST`
        """
        model = WorkflowAST()
        if include_optional:
            return WorkflowAST(
                id = '0',
                name = '0',
                input_schema = '',
                nodes = [
                    nativebpm_client.models.node_ast.NodeAST(
                        id = '0', 
                        name = '', 
                        type = 'startEvent', 
                        topic = '', 
                        wasm_path = '', 
                        provider = '', 
                        model = '', 
                        prompt = '', 
                        system_instruction = '', 
                        response_schema = '', 
                        temperature = 1.337, 
                        result_var = '', 
                        assignee = '', 
                        candidate_groups = '', 
                        due_date = '', 
                        input_schema = '', 
                        form_id = '', 
                        form_key = '', 
                        called_element = '', 
                        in_variables = [
                            nativebpm_client.models.in_variable.InVariable(
                                source = '', 
                                target = '', 
                                variables = '', 
                                local = True, )
                            ], 
                        out_variables = [
                            nativebpm_client.models.out_variable.OutVariable(
                                source = '', 
                                target = '', 
                                variables = '', )
                            ], 
                        decision_ref = '', 
                        map_decision_result = '', 
                        hit_policy = '', 
                        inputs = [
                            nativebpm_client.models.dmn_input_ast.DMNInputAST(
                                expression = '', 
                                type = '', )
                            ], 
                        outputs = [
                            nativebpm_client.models.dmn_output_ast.DMNOutputAST(
                                name = '', 
                                type = '', )
                            ], 
                        rules = [
                            nativebpm_client.models.dmn_rule_ast.DMNRuleAST(
                                inputs = [
                                    ''
                                    ], 
                                outputs = [
                                    ''
                                    ], )
                            ], 
                        attached_to_ref = '', 
                        time_duration = '', 
                        time_date = '', 
                        time_cycle = '', 
                        cancel_activity = True, )
                    ],
                flows = [
                    nativebpm_client.models.flow_ast.FlowAST(
                        id = '0', 
                        source = '0', 
                        target = '0', 
                        condition = '', )
                    ]
            )
        else:
            return WorkflowAST(
                id = '0',
                name = '0',
                nodes = [
                    nativebpm_client.models.node_ast.NodeAST(
                        id = '0', 
                        name = '', 
                        type = 'startEvent', 
                        topic = '', 
                        wasm_path = '', 
                        provider = '', 
                        model = '', 
                        prompt = '', 
                        system_instruction = '', 
                        response_schema = '', 
                        temperature = 1.337, 
                        result_var = '', 
                        assignee = '', 
                        candidate_groups = '', 
                        due_date = '', 
                        input_schema = '', 
                        form_id = '', 
                        form_key = '', 
                        called_element = '', 
                        in_variables = [
                            nativebpm_client.models.in_variable.InVariable(
                                source = '', 
                                target = '', 
                                variables = '', 
                                local = True, )
                            ], 
                        out_variables = [
                            nativebpm_client.models.out_variable.OutVariable(
                                source = '', 
                                target = '', 
                                variables = '', )
                            ], 
                        decision_ref = '', 
                        map_decision_result = '', 
                        hit_policy = '', 
                        inputs = [
                            nativebpm_client.models.dmn_input_ast.DMNInputAST(
                                expression = '', 
                                type = '', )
                            ], 
                        outputs = [
                            nativebpm_client.models.dmn_output_ast.DMNOutputAST(
                                name = '', 
                                type = '', )
                            ], 
                        rules = [
                            nativebpm_client.models.dmn_rule_ast.DMNRuleAST(
                                inputs = [
                                    ''
                                    ], 
                                outputs = [
                                    ''
                                    ], )
                            ], 
                        attached_to_ref = '', 
                        time_duration = '', 
                        time_date = '', 
                        time_cycle = '', 
                        cancel_activity = True, )
                    ],
                flows = [
                    nativebpm_client.models.flow_ast.FlowAST(
                        id = '0', 
                        source = '0', 
                        target = '0', 
                        condition = '', )
                    ],
        )
        """

    def testWorkflowAST(self):
        """Test WorkflowAST"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
