# coding: utf-8

"""
    NativeBPM Engine REST API

    REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nativebpm_client.models.visualization_data import VisualizationData

class TestVisualizationData(unittest.TestCase):
    """VisualizationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VisualizationData:
        """Test VisualizationData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VisualizationData`
        """
        model = VisualizationData()
        if include_optional:
            return VisualizationData(
                instance_id = '',
                definition_id = '',
                xml = '',
                active_nodes = [
                    ''
                    ],
                waiting_nodes = [
                    ''
                    ],
                completed_nodes = [
                    ''
                    ],
                history = [
                    nativebpm_client.models.history_record.HistoryRecord(
                        id = '', 
                        instance_id = '', 
                        node_id = '', 
                        node_name = '', 
                        node_type = '', 
                        action = 'start', 
                        variables = 'YQ==', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                completed = True
            )
        else:
            return VisualizationData(
                instance_id = '',
                definition_id = '',
                xml = '',
                active_nodes = [
                    ''
                    ],
                waiting_nodes = [
                    ''
                    ],
                completed_nodes = [
                    ''
                    ],
                history = [
                    nativebpm_client.models.history_record.HistoryRecord(
                        id = '', 
                        instance_id = '', 
                        node_id = '', 
                        node_name = '', 
                        node_type = '', 
                        action = 'start', 
                        variables = 'YQ==', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                completed = True,
        )
        """

    def testVisualizationData(self):
        """Test VisualizationData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
