# coding: utf-8

"""
    NativeBPM Engine REST API

    REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nativebpm_client.models.dmn_output_ast import DMNOutputAST

class TestDMNOutputAST(unittest.TestCase):
    """DMNOutputAST unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DMNOutputAST:
        """Test DMNOutputAST
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DMNOutputAST`
        """
        model = DMNOutputAST()
        if include_optional:
            return DMNOutputAST(
                name = '',
                type = ''
            )
        else:
            return DMNOutputAST(
                name = '',
                type = '',
        )
        """

    def testDMNOutputAST(self):
        """Test DMNOutputAST"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
