//
// CompleteInstanceTaskRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CompleteInstanceTaskRequest: Codable, JSONEncodable, Hashable {

    /** BPMN task element identifier */
    public var nodeId: String
    public var variables: [String: AnyCodable]?

    public init(nodeId: String, variables: [String: AnyCodable]? = nil) {
        self.nodeId = nodeId
        self.variables = variables
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nodeId = "node_id"
        case variables
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nodeId, forKey: .nodeId)
        try container.encodeIfPresent(variables, forKey: .variables)
    }
}

