//
// HistoryRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryRecord: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var instanceId: UUID
    public var nodeId: String
    public var nodeName: String
    public var nodeType: String
    public var action: String
    /** JSON encoded payload variables associated with this transition */
    public var variables: Data?
    public var timestamp: Date

    public init(id: UUID, instanceId: UUID, nodeId: String, nodeName: String, nodeType: String, action: String, variables: Data? = nil, timestamp: Date) {
        self.id = id
        self.instanceId = instanceId
        self.nodeId = nodeId
        self.nodeName = nodeName
        self.nodeType = nodeType
        self.action = action
        self.variables = variables
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case instanceId = "instance_id"
        case nodeId = "node_id"
        case nodeName = "node_name"
        case nodeType = "node_type"
        case action
        case variables
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(instanceId, forKey: .instanceId)
        try container.encode(nodeId, forKey: .nodeId)
        try container.encode(nodeName, forKey: .nodeName)
        try container.encode(nodeType, forKey: .nodeType)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(variables, forKey: .variables)
        try container.encode(timestamp, forKey: .timestamp)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension HistoryRecord: Identifiable {}
