//
// InVariable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InVariable: Codable, JSONEncodable, Hashable {

    public var source: String?
    public var target: String?
    public var variables: String?
    public var local: Bool?

    public init(source: String? = nil, target: String? = nil, variables: String? = nil, local: Bool? = nil) {
        self.source = source
        self.target = target
        self.variables = variables
        self.local = local
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case target
        case variables
        case local
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(target, forKey: .target)
        try container.encodeIfPresent(variables, forKey: .variables)
        try container.encodeIfPresent(local, forKey: .local)
    }
}

