//
// WebhookRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebhookRecord: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var tenantId: String
    public var url: String
    public var secret: String?
    public var events: [String]
    public var processId: String?
    public var isActive: Bool
    public var enableAudit: Bool
    public var status: String
    public var createdAt: Date

    public init(id: UUID, tenantId: String, url: String, secret: String? = nil, events: [String], processId: String? = nil, isActive: Bool, enableAudit: Bool, status: String, createdAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.url = url
        self.secret = secret
        self.events = events
        self.processId = processId
        self.isActive = isActive
        self.enableAudit = enableAudit
        self.status = status
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case url
        case secret
        case events
        case processId = "process_id"
        case isActive = "is_active"
        case enableAudit = "enable_audit"
        case status
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encode(events, forKey: .events)
        try container.encodeIfPresent(processId, forKey: .processId)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(enableAudit, forKey: .enableAudit)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension WebhookRecord: Identifiable {}
