<?php
/**
 * NodeAST
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NativeBPMClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NativeBPMClient\Model;

use \ArrayAccess;
use \NativeBPMClient\ObjectSerializer;

/**
 * NodeAST Class Doc Comment
 *
 * @category Class
 * @package  NativeBPMClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NodeAST implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'NodeAST';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'type' => 'string',
        'topic' => 'string',
        'wasm_path' => 'string',
        'provider' => 'string',
        'model' => 'string',
        'prompt' => 'string',
        'system_instruction' => 'string',
        'response_schema' => 'string',
        'temperature' => 'float',
        'result_var' => 'string',
        'assignee' => 'string',
        'candidate_groups' => 'string',
        'due_date' => 'string',
        'input_schema' => 'string',
        'form_id' => 'string',
        'form_key' => 'string',
        'called_element' => 'string',
        'in_variables' => '\NativeBPMClient\Model\InVariable[]',
        'out_variables' => '\NativeBPMClient\Model\OutVariable[]',
        'decision_ref' => 'string',
        'map_decision_result' => 'string',
        'hit_policy' => 'string',
        'inputs' => '\NativeBPMClient\Model\DMNInputAST[]',
        'outputs' => '\NativeBPMClient\Model\DMNOutputAST[]',
        'rules' => '\NativeBPMClient\Model\DMNRuleAST[]',
        'attached_to_ref' => 'string',
        'time_duration' => 'string',
        'time_date' => 'string',
        'time_cycle' => 'string',
        'cancel_activity' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'type' => null,
        'topic' => null,
        'wasm_path' => null,
        'provider' => null,
        'model' => null,
        'prompt' => null,
        'system_instruction' => null,
        'response_schema' => null,
        'temperature' => null,
        'result_var' => null,
        'assignee' => null,
        'candidate_groups' => null,
        'due_date' => null,
        'input_schema' => null,
        'form_id' => null,
        'form_key' => null,
        'called_element' => null,
        'in_variables' => null,
        'out_variables' => null,
        'decision_ref' => null,
        'map_decision_result' => null,
        'hit_policy' => null,
        'inputs' => null,
        'outputs' => null,
        'rules' => null,
        'attached_to_ref' => null,
        'time_duration' => null,
        'time_date' => null,
        'time_cycle' => null,
        'cancel_activity' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'type' => false,
        'topic' => false,
        'wasm_path' => false,
        'provider' => false,
        'model' => false,
        'prompt' => false,
        'system_instruction' => false,
        'response_schema' => false,
        'temperature' => false,
        'result_var' => false,
        'assignee' => false,
        'candidate_groups' => false,
        'due_date' => false,
        'input_schema' => false,
        'form_id' => false,
        'form_key' => false,
        'called_element' => false,
        'in_variables' => false,
        'out_variables' => false,
        'decision_ref' => false,
        'map_decision_result' => false,
        'hit_policy' => false,
        'inputs' => false,
        'outputs' => false,
        'rules' => false,
        'attached_to_ref' => false,
        'time_duration' => false,
        'time_date' => false,
        'time_cycle' => false,
        'cancel_activity' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'type' => 'type',
        'topic' => 'topic',
        'wasm_path' => 'wasmPath',
        'provider' => 'provider',
        'model' => 'model',
        'prompt' => 'prompt',
        'system_instruction' => 'systemInstruction',
        'response_schema' => 'responseSchema',
        'temperature' => 'temperature',
        'result_var' => 'resultVar',
        'assignee' => 'assignee',
        'candidate_groups' => 'candidateGroups',
        'due_date' => 'dueDate',
        'input_schema' => 'inputSchema',
        'form_id' => 'formId',
        'form_key' => 'formKey',
        'called_element' => 'calledElement',
        'in_variables' => 'inVariables',
        'out_variables' => 'outVariables',
        'decision_ref' => 'decisionRef',
        'map_decision_result' => 'mapDecisionResult',
        'hit_policy' => 'hitPolicy',
        'inputs' => 'inputs',
        'outputs' => 'outputs',
        'rules' => 'rules',
        'attached_to_ref' => 'attachedToRef',
        'time_duration' => 'timeDuration',
        'time_date' => 'timeDate',
        'time_cycle' => 'timeCycle',
        'cancel_activity' => 'cancelActivity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'type' => 'setType',
        'topic' => 'setTopic',
        'wasm_path' => 'setWasmPath',
        'provider' => 'setProvider',
        'model' => 'setModel',
        'prompt' => 'setPrompt',
        'system_instruction' => 'setSystemInstruction',
        'response_schema' => 'setResponseSchema',
        'temperature' => 'setTemperature',
        'result_var' => 'setResultVar',
        'assignee' => 'setAssignee',
        'candidate_groups' => 'setCandidateGroups',
        'due_date' => 'setDueDate',
        'input_schema' => 'setInputSchema',
        'form_id' => 'setFormId',
        'form_key' => 'setFormKey',
        'called_element' => 'setCalledElement',
        'in_variables' => 'setInVariables',
        'out_variables' => 'setOutVariables',
        'decision_ref' => 'setDecisionRef',
        'map_decision_result' => 'setMapDecisionResult',
        'hit_policy' => 'setHitPolicy',
        'inputs' => 'setInputs',
        'outputs' => 'setOutputs',
        'rules' => 'setRules',
        'attached_to_ref' => 'setAttachedToRef',
        'time_duration' => 'setTimeDuration',
        'time_date' => 'setTimeDate',
        'time_cycle' => 'setTimeCycle',
        'cancel_activity' => 'setCancelActivity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'type' => 'getType',
        'topic' => 'getTopic',
        'wasm_path' => 'getWasmPath',
        'provider' => 'getProvider',
        'model' => 'getModel',
        'prompt' => 'getPrompt',
        'system_instruction' => 'getSystemInstruction',
        'response_schema' => 'getResponseSchema',
        'temperature' => 'getTemperature',
        'result_var' => 'getResultVar',
        'assignee' => 'getAssignee',
        'candidate_groups' => 'getCandidateGroups',
        'due_date' => 'getDueDate',
        'input_schema' => 'getInputSchema',
        'form_id' => 'getFormId',
        'form_key' => 'getFormKey',
        'called_element' => 'getCalledElement',
        'in_variables' => 'getInVariables',
        'out_variables' => 'getOutVariables',
        'decision_ref' => 'getDecisionRef',
        'map_decision_result' => 'getMapDecisionResult',
        'hit_policy' => 'getHitPolicy',
        'inputs' => 'getInputs',
        'outputs' => 'getOutputs',
        'rules' => 'getRules',
        'attached_to_ref' => 'getAttachedToRef',
        'time_duration' => 'getTimeDuration',
        'time_date' => 'getTimeDate',
        'time_cycle' => 'getTimeCycle',
        'cancel_activity' => 'getCancelActivity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_START_EVENT = 'startEvent';
    public const TYPE_END_EVENT = 'endEvent';
    public const TYPE_SERVICE_TASK = 'serviceTask';
    public const TYPE_USER_TASK = 'userTask';
    public const TYPE_AI_SERVICE_TASK = 'aiServiceTask';
    public const TYPE_AI_TASK = 'aiTask';
    public const TYPE_EXCLUSIVE_GATEWAY = 'exclusiveGateway';
    public const TYPE_PARALLEL_GATEWAY = 'parallelGateway';
    public const TYPE_EVENT_BASED_GATEWAY = 'eventBasedGateway';
    public const TYPE_CALL_ACTIVITY = 'callActivity';
    public const TYPE_BUSINESS_RULE_TASK = 'businessRuleTask';
    public const TYPE_BOUNDARY_TIMER_EVENT = 'boundaryTimerEvent';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_START_EVENT,
            self::TYPE_END_EVENT,
            self::TYPE_SERVICE_TASK,
            self::TYPE_USER_TASK,
            self::TYPE_AI_SERVICE_TASK,
            self::TYPE_AI_TASK,
            self::TYPE_EXCLUSIVE_GATEWAY,
            self::TYPE_PARALLEL_GATEWAY,
            self::TYPE_EVENT_BASED_GATEWAY,
            self::TYPE_CALL_ACTIVITY,
            self::TYPE_BUSINESS_RULE_TASK,
            self::TYPE_BOUNDARY_TIMER_EVENT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('topic', $data ?? [], null);
        $this->setIfExists('wasm_path', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('prompt', $data ?? [], null);
        $this->setIfExists('system_instruction', $data ?? [], null);
        $this->setIfExists('response_schema', $data ?? [], null);
        $this->setIfExists('temperature', $data ?? [], null);
        $this->setIfExists('result_var', $data ?? [], null);
        $this->setIfExists('assignee', $data ?? [], null);
        $this->setIfExists('candidate_groups', $data ?? [], null);
        $this->setIfExists('due_date', $data ?? [], null);
        $this->setIfExists('input_schema', $data ?? [], null);
        $this->setIfExists('form_id', $data ?? [], null);
        $this->setIfExists('form_key', $data ?? [], null);
        $this->setIfExists('called_element', $data ?? [], null);
        $this->setIfExists('in_variables', $data ?? [], null);
        $this->setIfExists('out_variables', $data ?? [], null);
        $this->setIfExists('decision_ref', $data ?? [], null);
        $this->setIfExists('map_decision_result', $data ?? [], null);
        $this->setIfExists('hit_policy', $data ?? [], null);
        $this->setIfExists('inputs', $data ?? [], null);
        $this->setIfExists('outputs', $data ?? [], null);
        $this->setIfExists('rules', $data ?? [], null);
        $this->setIfExists('attached_to_ref', $data ?? [], null);
        $this->setIfExists('time_duration', $data ?? [], null);
        $this->setIfExists('time_date', $data ?? [], null);
        $this->setIfExists('time_cycle', $data ?? [], null);
        $this->setIfExists('cancel_activity', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) < 1)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        if ((mb_strlen($id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id when calling NodeAST., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets topic
     *
     * @return string|null
     */
    public function getTopic()
    {
        return $this->container['topic'];
    }

    /**
     * Sets topic
     *
     * @param string|null $topic topic
     *
     * @return self
     */
    public function setTopic($topic)
    {
        if (is_null($topic)) {
            throw new \InvalidArgumentException('non-nullable topic cannot be null');
        }
        $this->container['topic'] = $topic;

        return $this;
    }

    /**
     * Gets wasm_path
     *
     * @return string|null
     */
    public function getWasmPath()
    {
        return $this->container['wasm_path'];
    }

    /**
     * Sets wasm_path
     *
     * @param string|null $wasm_path wasm_path
     *
     * @return self
     */
    public function setWasmPath($wasm_path)
    {
        if (is_null($wasm_path)) {
            throw new \InvalidArgumentException('non-nullable wasm_path cannot be null');
        }
        $this->container['wasm_path'] = $wasm_path;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return string|null
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param string|null $provider provider
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            throw new \InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string|null $model model
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            throw new \InvalidArgumentException('non-nullable model cannot be null');
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets prompt
     *
     * @return string|null
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }

    /**
     * Sets prompt
     *
     * @param string|null $prompt prompt
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }
        $this->container['prompt'] = $prompt;

        return $this;
    }

    /**
     * Gets system_instruction
     *
     * @return string|null
     */
    public function getSystemInstruction()
    {
        return $this->container['system_instruction'];
    }

    /**
     * Sets system_instruction
     *
     * @param string|null $system_instruction system_instruction
     *
     * @return self
     */
    public function setSystemInstruction($system_instruction)
    {
        if (is_null($system_instruction)) {
            throw new \InvalidArgumentException('non-nullable system_instruction cannot be null');
        }
        $this->container['system_instruction'] = $system_instruction;

        return $this;
    }

    /**
     * Gets response_schema
     *
     * @return string|null
     */
    public function getResponseSchema()
    {
        return $this->container['response_schema'];
    }

    /**
     * Sets response_schema
     *
     * @param string|null $response_schema response_schema
     *
     * @return self
     */
    public function setResponseSchema($response_schema)
    {
        if (is_null($response_schema)) {
            throw new \InvalidArgumentException('non-nullable response_schema cannot be null');
        }
        $this->container['response_schema'] = $response_schema;

        return $this;
    }

    /**
     * Gets temperature
     *
     * @return float|null
     */
    public function getTemperature()
    {
        return $this->container['temperature'];
    }

    /**
     * Sets temperature
     *
     * @param float|null $temperature temperature
     *
     * @return self
     */
    public function setTemperature($temperature)
    {
        if (is_null($temperature)) {
            throw new \InvalidArgumentException('non-nullable temperature cannot be null');
        }
        $this->container['temperature'] = $temperature;

        return $this;
    }

    /**
     * Gets result_var
     *
     * @return string|null
     */
    public function getResultVar()
    {
        return $this->container['result_var'];
    }

    /**
     * Sets result_var
     *
     * @param string|null $result_var result_var
     *
     * @return self
     */
    public function setResultVar($result_var)
    {
        if (is_null($result_var)) {
            throw new \InvalidArgumentException('non-nullable result_var cannot be null');
        }
        $this->container['result_var'] = $result_var;

        return $this;
    }

    /**
     * Gets assignee
     *
     * @return string|null
     */
    public function getAssignee()
    {
        return $this->container['assignee'];
    }

    /**
     * Sets assignee
     *
     * @param string|null $assignee assignee
     *
     * @return self
     */
    public function setAssignee($assignee)
    {
        if (is_null($assignee)) {
            throw new \InvalidArgumentException('non-nullable assignee cannot be null');
        }
        $this->container['assignee'] = $assignee;

        return $this;
    }

    /**
     * Gets candidate_groups
     *
     * @return string|null
     */
    public function getCandidateGroups()
    {
        return $this->container['candidate_groups'];
    }

    /**
     * Sets candidate_groups
     *
     * @param string|null $candidate_groups candidate_groups
     *
     * @return self
     */
    public function setCandidateGroups($candidate_groups)
    {
        if (is_null($candidate_groups)) {
            throw new \InvalidArgumentException('non-nullable candidate_groups cannot be null');
        }
        $this->container['candidate_groups'] = $candidate_groups;

        return $this;
    }

    /**
     * Gets due_date
     *
     * @return string|null
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     *
     * @param string|null $due_date due_date
     *
     * @return self
     */
    public function setDueDate($due_date)
    {
        if (is_null($due_date)) {
            throw new \InvalidArgumentException('non-nullable due_date cannot be null');
        }
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets input_schema
     *
     * @return string|null
     */
    public function getInputSchema()
    {
        return $this->container['input_schema'];
    }

    /**
     * Sets input_schema
     *
     * @param string|null $input_schema input_schema
     *
     * @return self
     */
    public function setInputSchema($input_schema)
    {
        if (is_null($input_schema)) {
            throw new \InvalidArgumentException('non-nullable input_schema cannot be null');
        }
        $this->container['input_schema'] = $input_schema;

        return $this;
    }

    /**
     * Gets form_id
     *
     * @return string|null
     */
    public function getFormId()
    {
        return $this->container['form_id'];
    }

    /**
     * Sets form_id
     *
     * @param string|null $form_id form_id
     *
     * @return self
     */
    public function setFormId($form_id)
    {
        if (is_null($form_id)) {
            throw new \InvalidArgumentException('non-nullable form_id cannot be null');
        }
        $this->container['form_id'] = $form_id;

        return $this;
    }

    /**
     * Gets form_key
     *
     * @return string|null
     */
    public function getFormKey()
    {
        return $this->container['form_key'];
    }

    /**
     * Sets form_key
     *
     * @param string|null $form_key form_key
     *
     * @return self
     */
    public function setFormKey($form_key)
    {
        if (is_null($form_key)) {
            throw new \InvalidArgumentException('non-nullable form_key cannot be null');
        }
        $this->container['form_key'] = $form_key;

        return $this;
    }

    /**
     * Gets called_element
     *
     * @return string|null
     */
    public function getCalledElement()
    {
        return $this->container['called_element'];
    }

    /**
     * Sets called_element
     *
     * @param string|null $called_element called_element
     *
     * @return self
     */
    public function setCalledElement($called_element)
    {
        if (is_null($called_element)) {
            throw new \InvalidArgumentException('non-nullable called_element cannot be null');
        }
        $this->container['called_element'] = $called_element;

        return $this;
    }

    /**
     * Gets in_variables
     *
     * @return \NativeBPMClient\Model\InVariable[]|null
     */
    public function getInVariables()
    {
        return $this->container['in_variables'];
    }

    /**
     * Sets in_variables
     *
     * @param \NativeBPMClient\Model\InVariable[]|null $in_variables in_variables
     *
     * @return self
     */
    public function setInVariables($in_variables)
    {
        if (is_null($in_variables)) {
            throw new \InvalidArgumentException('non-nullable in_variables cannot be null');
        }
        $this->container['in_variables'] = $in_variables;

        return $this;
    }

    /**
     * Gets out_variables
     *
     * @return \NativeBPMClient\Model\OutVariable[]|null
     */
    public function getOutVariables()
    {
        return $this->container['out_variables'];
    }

    /**
     * Sets out_variables
     *
     * @param \NativeBPMClient\Model\OutVariable[]|null $out_variables out_variables
     *
     * @return self
     */
    public function setOutVariables($out_variables)
    {
        if (is_null($out_variables)) {
            throw new \InvalidArgumentException('non-nullable out_variables cannot be null');
        }
        $this->container['out_variables'] = $out_variables;

        return $this;
    }

    /**
     * Gets decision_ref
     *
     * @return string|null
     */
    public function getDecisionRef()
    {
        return $this->container['decision_ref'];
    }

    /**
     * Sets decision_ref
     *
     * @param string|null $decision_ref decision_ref
     *
     * @return self
     */
    public function setDecisionRef($decision_ref)
    {
        if (is_null($decision_ref)) {
            throw new \InvalidArgumentException('non-nullable decision_ref cannot be null');
        }
        $this->container['decision_ref'] = $decision_ref;

        return $this;
    }

    /**
     * Gets map_decision_result
     *
     * @return string|null
     */
    public function getMapDecisionResult()
    {
        return $this->container['map_decision_result'];
    }

    /**
     * Sets map_decision_result
     *
     * @param string|null $map_decision_result map_decision_result
     *
     * @return self
     */
    public function setMapDecisionResult($map_decision_result)
    {
        if (is_null($map_decision_result)) {
            throw new \InvalidArgumentException('non-nullable map_decision_result cannot be null');
        }
        $this->container['map_decision_result'] = $map_decision_result;

        return $this;
    }

    /**
     * Gets hit_policy
     *
     * @return string|null
     */
    public function getHitPolicy()
    {
        return $this->container['hit_policy'];
    }

    /**
     * Sets hit_policy
     *
     * @param string|null $hit_policy hit_policy
     *
     * @return self
     */
    public function setHitPolicy($hit_policy)
    {
        if (is_null($hit_policy)) {
            throw new \InvalidArgumentException('non-nullable hit_policy cannot be null');
        }
        $this->container['hit_policy'] = $hit_policy;

        return $this;
    }

    /**
     * Gets inputs
     *
     * @return \NativeBPMClient\Model\DMNInputAST[]|null
     */
    public function getInputs()
    {
        return $this->container['inputs'];
    }

    /**
     * Sets inputs
     *
     * @param \NativeBPMClient\Model\DMNInputAST[]|null $inputs inputs
     *
     * @return self
     */
    public function setInputs($inputs)
    {
        if (is_null($inputs)) {
            throw new \InvalidArgumentException('non-nullable inputs cannot be null');
        }
        $this->container['inputs'] = $inputs;

        return $this;
    }

    /**
     * Gets outputs
     *
     * @return \NativeBPMClient\Model\DMNOutputAST[]|null
     */
    public function getOutputs()
    {
        return $this->container['outputs'];
    }

    /**
     * Sets outputs
     *
     * @param \NativeBPMClient\Model\DMNOutputAST[]|null $outputs outputs
     *
     * @return self
     */
    public function setOutputs($outputs)
    {
        if (is_null($outputs)) {
            throw new \InvalidArgumentException('non-nullable outputs cannot be null');
        }
        $this->container['outputs'] = $outputs;

        return $this;
    }

    /**
     * Gets rules
     *
     * @return \NativeBPMClient\Model\DMNRuleAST[]|null
     */
    public function getRules()
    {
        return $this->container['rules'];
    }

    /**
     * Sets rules
     *
     * @param \NativeBPMClient\Model\DMNRuleAST[]|null $rules rules
     *
     * @return self
     */
    public function setRules($rules)
    {
        if (is_null($rules)) {
            throw new \InvalidArgumentException('non-nullable rules cannot be null');
        }
        $this->container['rules'] = $rules;

        return $this;
    }

    /**
     * Gets attached_to_ref
     *
     * @return string|null
     */
    public function getAttachedToRef()
    {
        return $this->container['attached_to_ref'];
    }

    /**
     * Sets attached_to_ref
     *
     * @param string|null $attached_to_ref attached_to_ref
     *
     * @return self
     */
    public function setAttachedToRef($attached_to_ref)
    {
        if (is_null($attached_to_ref)) {
            throw new \InvalidArgumentException('non-nullable attached_to_ref cannot be null');
        }
        $this->container['attached_to_ref'] = $attached_to_ref;

        return $this;
    }

    /**
     * Gets time_duration
     *
     * @return string|null
     */
    public function getTimeDuration()
    {
        return $this->container['time_duration'];
    }

    /**
     * Sets time_duration
     *
     * @param string|null $time_duration time_duration
     *
     * @return self
     */
    public function setTimeDuration($time_duration)
    {
        if (is_null($time_duration)) {
            throw new \InvalidArgumentException('non-nullable time_duration cannot be null');
        }
        $this->container['time_duration'] = $time_duration;

        return $this;
    }

    /**
     * Gets time_date
     *
     * @return string|null
     */
    public function getTimeDate()
    {
        return $this->container['time_date'];
    }

    /**
     * Sets time_date
     *
     * @param string|null $time_date time_date
     *
     * @return self
     */
    public function setTimeDate($time_date)
    {
        if (is_null($time_date)) {
            throw new \InvalidArgumentException('non-nullable time_date cannot be null');
        }
        $this->container['time_date'] = $time_date;

        return $this;
    }

    /**
     * Gets time_cycle
     *
     * @return string|null
     */
    public function getTimeCycle()
    {
        return $this->container['time_cycle'];
    }

    /**
     * Sets time_cycle
     *
     * @param string|null $time_cycle time_cycle
     *
     * @return self
     */
    public function setTimeCycle($time_cycle)
    {
        if (is_null($time_cycle)) {
            throw new \InvalidArgumentException('non-nullable time_cycle cannot be null');
        }
        $this->container['time_cycle'] = $time_cycle;

        return $this;
    }

    /**
     * Gets cancel_activity
     *
     * @return bool|null
     */
    public function getCancelActivity()
    {
        return $this->container['cancel_activity'];
    }

    /**
     * Sets cancel_activity
     *
     * @param bool|null $cancel_activity cancel_activity
     *
     * @return self
     */
    public function setCancelActivity($cancel_activity)
    {
        if (is_null($cancel_activity)) {
            throw new \InvalidArgumentException('non-nullable cancel_activity cannot be null');
        }
        $this->container['cancel_activity'] = $cancel_activity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


