/* tslint:disable */
/* eslint-disable */
/**
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookRequest
 */
export interface CreateWebhookRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookRequest
     */
    secret?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateWebhookRequest
     */
    events: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookRequest
     */
    processId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateWebhookRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateWebhookRequest
     */
    enableAudit?: boolean;
}

/**
 * Check if a given object implements the CreateWebhookRequest interface.
 */
export function instanceOfCreateWebhookRequest(value: object): value is CreateWebhookRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function CreateWebhookRequestFromJSON(json: any): CreateWebhookRequest {
    return CreateWebhookRequestFromJSONTyped(json, false);
}

export function CreateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'events': json['events'],
        'processId': json['process_id'] == null ? undefined : json['process_id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'enableAudit': json['enable_audit'] == null ? undefined : json['enable_audit'],
    };
}

export function CreateWebhookRequestToJSON(json: any): CreateWebhookRequest {
    return CreateWebhookRequestToJSONTyped(json, false);
}

export function CreateWebhookRequestToJSONTyped(value?: CreateWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'secret': value['secret'],
        'events': value['events'],
        'process_id': value['processId'],
        'is_active': value['isActive'],
        'enable_audit': value['enableAudit'],
    };
}

