/* tslint:disable */
/* eslint-disable */
/**
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteWebhook200Response
 */
export interface DeleteWebhook200Response {
    /**
     * 
     */
    status?: string;
}

/**
 * Check if a given object implements the DeleteWebhook200Response interface.
 */
export function instanceOfDeleteWebhook200Response(value: object): value is DeleteWebhook200Response {
    return true;
}

export function DeleteWebhook200ResponseFromJSON(json: any): DeleteWebhook200Response {
    return DeleteWebhook200ResponseFromJSONTyped(json, false);
}

export function DeleteWebhook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteWebhook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function DeleteWebhook200ResponseToJSON(json: any): DeleteWebhook200Response {
    return DeleteWebhook200ResponseToJSONTyped(json, false);
}

export function DeleteWebhook200ResponseToJSONTyped(value?: DeleteWebhook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

