/* tslint:disable */
/* eslint-disable */
/**
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DMNInputAST
 */
export interface DMNInputAST {
    /**
     * 
     */
    expression: string;
    /**
     * 
     */
    type: string;
}

/**
 * Check if a given object implements the DMNInputAST interface.
 */
export function instanceOfDMNInputAST(value: object): value is DMNInputAST {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function DMNInputASTFromJSON(json: any): DMNInputAST {
    return DMNInputASTFromJSONTyped(json, false);
}

export function DMNInputASTFromJSONTyped(json: any, ignoreDiscriminator: boolean): DMNInputAST {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'],
        'type': json['type'],
    };
}

export function DMNInputASTToJSON(json: any): DMNInputAST {
    return DMNInputASTToJSONTyped(json, false);
}

export function DMNInputASTToJSONTyped(value?: DMNInputAST | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expression': value['expression'],
        'type': value['type'],
    };
}

