/* tslint:disable */
/* eslint-disable */
/**
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DMNRuleAST
 */
export interface DMNRuleAST {
    /**
     * 
     */
    inputs: Array<string>;
    /**
     * 
     */
    outputs: Array<string>;
}

/**
 * Check if a given object implements the DMNRuleAST interface.
 */
export function instanceOfDMNRuleAST(value: object): value is DMNRuleAST {
    if (!('inputs' in value) || value['inputs'] === undefined) return false;
    if (!('outputs' in value) || value['outputs'] === undefined) return false;
    return true;
}

export function DMNRuleASTFromJSON(json: any): DMNRuleAST {
    return DMNRuleASTFromJSONTyped(json, false);
}

export function DMNRuleASTFromJSONTyped(json: any, ignoreDiscriminator: boolean): DMNRuleAST {
    if (json == null) {
        return json;
    }
    return {
        
        'inputs': json['inputs'],
        'outputs': json['outputs'],
    };
}

export function DMNRuleASTToJSON(json: any): DMNRuleAST {
    return DMNRuleASTToJSONTyped(json, false);
}

export function DMNRuleASTToJSONTyped(value?: DMNRuleAST | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inputs': value['inputs'],
        'outputs': value['outputs'],
    };
}

