/* tslint:disable */
/* eslint-disable */
/**
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface IncidentRecord
 */
export interface IncidentRecord {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    instanceId: string;
    /**
     * 
     */
    activityId: string;
    /**
     * 
     */
    errorMessage: string;
    /**
     * 
     */
    stackTrace?: string;
    /**
     * 
     */
    attemptsMade: number;
    /**
     * 
     */
    resolved: boolean;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    resolvedAt?: Date;
}

/**
 * Check if a given object implements the IncidentRecord interface.
 */
export function instanceOfIncidentRecord(value: object): value is IncidentRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('instanceId' in (value as Record<string, any>)) && !('instance_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['instanceId'] === undefined && (value as Record<string, any>)['instance_id'] === undefined)) return false;
    if ((!('activityId' in (value as Record<string, any>)) && !('activity_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['activityId'] === undefined && (value as Record<string, any>)['activity_id'] === undefined)) return false;
    if ((!('errorMessage' in (value as Record<string, any>)) && !('error_message' in (value as Record<string, any>))) || ((value as Record<string, any>)['errorMessage'] === undefined && (value as Record<string, any>)['error_message'] === undefined)) return false;
    if ((!('attemptsMade' in (value as Record<string, any>)) && !('attempts_made' in (value as Record<string, any>))) || ((value as Record<string, any>)['attemptsMade'] === undefined && (value as Record<string, any>)['attempts_made'] === undefined)) return false;
    if (!('resolved' in value) || value['resolved'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function IncidentRecordFromJSON(json: any): IncidentRecord {
    return IncidentRecordFromJSONTyped(json, false);
}

export function IncidentRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'instanceId': json['instance_id'],
        'activityId': json['activity_id'],
        'errorMessage': json['error_message'],
        'stackTrace': json['stack_trace'] == null ? undefined : json['stack_trace'],
        'attemptsMade': json['attempts_made'],
        'resolved': json['resolved'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'resolvedAt': json['resolved_at'] == null ? undefined : (parseDateTime(json['resolved_at'])),
    };
}

export function IncidentRecordToJSON(json: any): IncidentRecord {
    return IncidentRecordToJSONTyped(json, false);
}

export function IncidentRecordToJSONTyped(value?: IncidentRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'instance_id': value['instanceId'],
        'activity_id': value['activityId'],
        'error_message': value['errorMessage'],
        'stack_trace': value['stackTrace'],
        'attempts_made': value['attemptsMade'],
        'resolved': value['resolved'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'resolved_at': value['resolvedAt'] == null ? value['resolvedAt'] : serializeDateTime(value['resolvedAt']),
    };
}

