/* tslint:disable */
/* eslint-disable */
/**
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoryRecord } from './HistoryRecord';
import {
    HistoryRecordFromJSON,
    HistoryRecordFromJSONTyped,
    HistoryRecordToJSON,
    HistoryRecordToJSONTyped,
} from './HistoryRecord';

/**
 * 
 * @export
 * @interface VisualizationData
 */
export interface VisualizationData {
    /**
     * 
     */
    instanceId: string;
    /**
     * 
     */
    definitionId: string;
    /**
     * 
     */
    xml: string;
    /**
     * 
     */
    activeNodes: Array<string>;
    /**
     * 
     */
    waitingNodes: Array<string>;
    /**
     * 
     */
    completedNodes: Array<string>;
    /**
     * 
     */
    history: Array<HistoryRecord>;
    /**
     * 
     */
    completed: boolean;
}

/**
 * Check if a given object implements the VisualizationData interface.
 */
export function instanceOfVisualizationData(value: object): value is VisualizationData {
    if ((!('instanceId' in (value as Record<string, any>)) && !('instance_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['instanceId'] === undefined && (value as Record<string, any>)['instance_id'] === undefined)) return false;
    if ((!('definitionId' in (value as Record<string, any>)) && !('definition_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['definitionId'] === undefined && (value as Record<string, any>)['definition_id'] === undefined)) return false;
    if (!('xml' in value) || value['xml'] === undefined) return false;
    if ((!('activeNodes' in (value as Record<string, any>)) && !('active_nodes' in (value as Record<string, any>))) || ((value as Record<string, any>)['activeNodes'] === undefined && (value as Record<string, any>)['active_nodes'] === undefined)) return false;
    if ((!('waitingNodes' in (value as Record<string, any>)) && !('waiting_nodes' in (value as Record<string, any>))) || ((value as Record<string, any>)['waitingNodes'] === undefined && (value as Record<string, any>)['waiting_nodes'] === undefined)) return false;
    if ((!('completedNodes' in (value as Record<string, any>)) && !('completed_nodes' in (value as Record<string, any>))) || ((value as Record<string, any>)['completedNodes'] === undefined && (value as Record<string, any>)['completed_nodes'] === undefined)) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    if (!('completed' in value) || value['completed'] === undefined) return false;
    return true;
}

export function VisualizationDataFromJSON(json: any): VisualizationData {
    return VisualizationDataFromJSONTyped(json, false);
}

export function VisualizationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisualizationData {
    if (json == null) {
        return json;
    }
    return {
        
        'instanceId': json['instance_id'],
        'definitionId': json['definition_id'],
        'xml': json['xml'],
        'activeNodes': json['active_nodes'],
        'waitingNodes': json['waiting_nodes'],
        'completedNodes': json['completed_nodes'],
        'history': ((json['history'] as Array<any>).map(HistoryRecordFromJSON)),
        'completed': json['completed'],
    };
}

export function VisualizationDataToJSON(json: any): VisualizationData {
    return VisualizationDataToJSONTyped(json, false);
}

export function VisualizationDataToJSONTyped(value?: VisualizationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instance_id': value['instanceId'],
        'definition_id': value['definitionId'],
        'xml': value['xml'],
        'active_nodes': value['activeNodes'],
        'waiting_nodes': value['waitingNodes'],
        'completed_nodes': value['completedNodes'],
        'history': ((value['history'] as Array<any>).map(HistoryRecordToJSON)),
        'completed': value['completed'],
    };
}

