/* tslint:disable */
/* eslint-disable */
/**
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookDeliveryRecord
 */
export interface WebhookDeliveryRecord {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    webhookId: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    eventType: string;
    /**
     * 
     */
    payload: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    responseCode?: number;
    /**
     * 
     */
    responseBody?: string;
    /**
     * 
     */
    attempts: number;
    /**
     * 
     */
    nextRetry?: Date;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    processedAt?: Date;
}

/**
 * Check if a given object implements the WebhookDeliveryRecord interface.
 */
export function instanceOfWebhookDeliveryRecord(value: object): value is WebhookDeliveryRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('webhookId' in (value as Record<string, any>)) && !('webhook_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['webhookId'] === undefined && (value as Record<string, any>)['webhook_id'] === undefined)) return false;
    if ((!('tenantId' in (value as Record<string, any>)) && !('tenant_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['tenantId'] === undefined && (value as Record<string, any>)['tenant_id'] === undefined)) return false;
    if ((!('eventType' in (value as Record<string, any>)) && !('event_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['eventType'] === undefined && (value as Record<string, any>)['event_type'] === undefined)) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function WebhookDeliveryRecordFromJSON(json: any): WebhookDeliveryRecord {
    return WebhookDeliveryRecordFromJSONTyped(json, false);
}

export function WebhookDeliveryRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'webhookId': json['webhook_id'],
        'tenantId': json['tenant_id'],
        'eventType': json['event_type'],
        'payload': json['payload'],
        'status': json['status'],
        'responseCode': json['response_code'] == null ? undefined : json['response_code'],
        'responseBody': json['response_body'] == null ? undefined : json['response_body'],
        'attempts': json['attempts'],
        'nextRetry': json['next_retry'] == null ? undefined : (parseDateTime(json['next_retry'])),
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'processedAt': json['processed_at'] == null ? undefined : (parseDateTime(json['processed_at'])),
    };
}

export function WebhookDeliveryRecordToJSON(json: any): WebhookDeliveryRecord {
    return WebhookDeliveryRecordToJSONTyped(json, false);
}

export function WebhookDeliveryRecordToJSONTyped(value?: WebhookDeliveryRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'webhook_id': value['webhookId'],
        'tenant_id': value['tenantId'],
        'event_type': value['eventType'],
        'payload': value['payload'],
        'status': value['status'],
        'response_code': value['responseCode'],
        'response_body': value['responseBody'],
        'attempts': value['attempts'],
        'next_retry': value['nextRetry'] == null ? value['nextRetry'] : serializeDateTime(value['nextRetry']),
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'processed_at': value['processedAt'] == null ? value['processedAt'] : serializeDateTime(value['processedAt']),
    };
}

