// <auto-generated>
/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using NativeBPM.Client.Client;

namespace NativeBPM.Client.Model
{
    /// <summary>
    /// CompleteTaskRequest
    /// </summary>
    public partial class CompleteTaskRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteTaskRequest" /> class.
        /// </summary>
        /// <param name="variables">variables</param>
        [JsonConstructor]
        public CompleteTaskRequest(Option<Dictionary<string, Object>?> variables = default)
        {
            VariablesOption = variables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Variables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> VariablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Variables
        /// </summary>
        [JsonPropertyName("variables")]
        public Dictionary<string, Object>? Variables { get { return this.VariablesOption.Value; } set { this.VariablesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompleteTaskRequest {\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CompleteTaskRequest" />
    /// </summary>
    public class CompleteTaskRequestJsonConverter : JsonConverter<CompleteTaskRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CompleteTaskRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CompleteTaskRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, Object>?> variables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "variables":
                            variables = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (variables.IsSet && variables.Value == null)
                throw new ArgumentNullException(nameof(variables), "Property is not nullable for class CompleteTaskRequest.");

            return new CompleteTaskRequest(variables);
        }

        /// <summary>
        /// Serializes a <see cref="CompleteTaskRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="completeTaskRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CompleteTaskRequest completeTaskRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, completeTaskRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CompleteTaskRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="completeTaskRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CompleteTaskRequest completeTaskRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (completeTaskRequest.VariablesOption.IsSet && completeTaskRequest.Variables == null)
                throw new ArgumentNullException(nameof(completeTaskRequest.Variables), "Property is required for class CompleteTaskRequest.");

            if (completeTaskRequest.VariablesOption.IsSet)
            {
                writer.WritePropertyName("variables");
                JsonSerializer.Serialize(writer, completeTaskRequest.Variables, jsonSerializerOptions);
            }
        }
    }
}
