// <auto-generated>
/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using NativeBPM.Client.Client;

namespace NativeBPM.Client.Model
{
    /// <summary>
    /// CreateWebhookRequest
    /// </summary>
    public partial class CreateWebhookRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateWebhookRequest" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="events">events</param>
        /// <param name="secret">secret</param>
        /// <param name="processId">processId</param>
        /// <param name="isActive">isActive</param>
        /// <param name="enableAudit">enableAudit</param>
        [JsonConstructor]
        public CreateWebhookRequest(string url, List<string> events, Option<string?> secret = default, Option<string?> processId = default, Option<bool?> isActive = default, Option<bool?> enableAudit = default)
        {
            Url = url;
            Events = events;
            SecretOption = secret;
            ProcessIdOption = processId;
            IsActiveOption = isActive;
            EnableAuditOption = enableAudit;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [JsonPropertyName("events")]
        public List<string> Events { get; set; }

        /// <summary>
        /// Used to track the state of Secret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SecretOption { get; private set; }

        /// <summary>
        /// Gets or Sets Secret
        /// </summary>
        [JsonPropertyName("secret")]
        public string? Secret { get { return this.SecretOption.Value; } set { this.SecretOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProcessId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProcessIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProcessId
        /// </summary>
        [JsonPropertyName("process_id")]
        public string? ProcessId { get { return this.ProcessIdOption.Value; } set { this.ProcessIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [JsonPropertyName("is_active")]
        public bool? IsActive { get { return this.IsActiveOption.Value; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableAudit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableAuditOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableAudit
        /// </summary>
        [JsonPropertyName("enable_audit")]
        public bool? EnableAudit { get { return this.EnableAuditOption.Value; } set { this.EnableAuditOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateWebhookRequest {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  ProcessId: ").Append(ProcessId).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  EnableAudit: ").Append(EnableAudit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateWebhookRequest" />
    /// </summary>
    public class CreateWebhookRequestJsonConverter : JsonConverter<CreateWebhookRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateWebhookRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateWebhookRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<List<string>?> events = default;
            Option<string?> secret = default;
            Option<string?> processId = default;
            Option<bool?> isActive = default;
            Option<bool?> enableAudit = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "events":
                            events = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "secret":
                            secret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "process_id":
                            processId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "is_active":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "enable_audit":
                            enableAudit = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class CreateWebhookRequest.", nameof(url));

            if (!events.IsSet)
                throw new ArgumentException("Property is required for class CreateWebhookRequest.", nameof(events));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class CreateWebhookRequest.");

            if (events.IsSet && events.Value == null)
                throw new ArgumentNullException(nameof(events), "Property is not nullable for class CreateWebhookRequest.");

            if (secret.IsSet && secret.Value == null)
                throw new ArgumentNullException(nameof(secret), "Property is not nullable for class CreateWebhookRequest.");

            if (processId.IsSet && processId.Value == null)
                throw new ArgumentNullException(nameof(processId), "Property is not nullable for class CreateWebhookRequest.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class CreateWebhookRequest.");

            if (enableAudit.IsSet && enableAudit.Value == null)
                throw new ArgumentNullException(nameof(enableAudit), "Property is not nullable for class CreateWebhookRequest.");

            return new CreateWebhookRequest(url.Value!, events.Value!, secret, processId, isActive, enableAudit);
        }

        /// <summary>
        /// Serializes a <see cref="CreateWebhookRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createWebhookRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateWebhookRequest createWebhookRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createWebhookRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateWebhookRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createWebhookRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateWebhookRequest createWebhookRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createWebhookRequest.Url == null)
                throw new ArgumentNullException(nameof(createWebhookRequest.Url), "Property is required for class CreateWebhookRequest.");

            if (createWebhookRequest.Events == null)
                throw new ArgumentNullException(nameof(createWebhookRequest.Events), "Property is required for class CreateWebhookRequest.");

            if (createWebhookRequest.SecretOption.IsSet && createWebhookRequest.Secret == null)
                throw new ArgumentNullException(nameof(createWebhookRequest.Secret), "Property is required for class CreateWebhookRequest.");

            if (createWebhookRequest.ProcessIdOption.IsSet && createWebhookRequest.ProcessId == null)
                throw new ArgumentNullException(nameof(createWebhookRequest.ProcessId), "Property is required for class CreateWebhookRequest.");

            writer.WriteString("url", createWebhookRequest.Url);

            writer.WritePropertyName("events");
            JsonSerializer.Serialize(writer, createWebhookRequest.Events, jsonSerializerOptions);
            if (createWebhookRequest.SecretOption.IsSet)
                writer.WriteString("secret", createWebhookRequest.Secret);

            if (createWebhookRequest.ProcessIdOption.IsSet)
                writer.WriteString("process_id", createWebhookRequest.ProcessId);

            if (createWebhookRequest.IsActiveOption.IsSet)
                writer.WriteBoolean("is_active", createWebhookRequest.IsActiveOption.Value!.Value);

            if (createWebhookRequest.EnableAuditOption.IsSet)
                writer.WriteBoolean("enable_audit", createWebhookRequest.EnableAuditOption.Value!.Value);
        }
    }
}
