// <auto-generated>
/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using NativeBPM.Client.Client;

namespace NativeBPM.Client.Model
{
    /// <summary>
    /// HistoryRecord
    /// </summary>
    public partial class HistoryRecord : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HistoryRecord" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="instanceId">instanceId</param>
        /// <param name="nodeId">nodeId</param>
        /// <param name="nodeName">nodeName</param>
        /// <param name="nodeType">nodeType</param>
        /// <param name="action">action</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="variables">JSON encoded payload variables associated with this transition</param>
        [JsonConstructor]
        public HistoryRecord(Guid id, Guid instanceId, string nodeId, string nodeName, string nodeType, string action, DateTime timestamp, Option<byte[]?> variables = default)
        {
            Id = id;
            InstanceId = instanceId;
            NodeId = nodeId;
            NodeName = nodeName;
            NodeType = nodeType;
            Action = action;
            Timestamp = timestamp;
            VariablesOption = variables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets InstanceId
        /// </summary>
        [JsonPropertyName("instance_id")]
        public Guid InstanceId { get; set; }

        /// <summary>
        /// Gets or Sets NodeId
        /// </summary>
        [JsonPropertyName("node_id")]
        public string NodeId { get; set; }

        /// <summary>
        /// Gets or Sets NodeName
        /// </summary>
        [JsonPropertyName("node_name")]
        public string NodeName { get; set; }

        /// <summary>
        /// Gets or Sets NodeType
        /// </summary>
        [JsonPropertyName("node_type")]
        public string NodeType { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        /* <example>start</example> */
        [JsonPropertyName("action")]
        public string Action { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Used to track the state of Variables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<byte[]?> VariablesOption { get; private set; }

        /// <summary>
        /// JSON encoded payload variables associated with this transition
        /// </summary>
        /// <value>JSON encoded payload variables associated with this transition</value>
        [JsonPropertyName("variables")]
        public byte[]? Variables { get { return this.VariablesOption.Value; } set { this.VariablesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HistoryRecord {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  NodeName: ").Append(NodeName).Append("\n");
            sb.Append("  NodeType: ").Append(NodeType).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HistoryRecord" />
    /// </summary>
    public class HistoryRecordJsonConverter : JsonConverter<HistoryRecord>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="HistoryRecord" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HistoryRecord Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> instanceId = default;
            Option<string?> nodeId = default;
            Option<string?> nodeName = default;
            Option<string?> nodeType = default;
            Option<string?> action = default;
            Option<DateTime?> timestamp = default;
            Option<byte[]?> variables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "instance_id":
                            instanceId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "node_id":
                            nodeId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "node_name":
                            nodeName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "node_type":
                            nodeType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action":
                            action = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "variables":
                            variables = new Option<byte[]?>(JsonSerializer.Deserialize<byte[]>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class HistoryRecord.", nameof(id));

            if (!instanceId.IsSet)
                throw new ArgumentException("Property is required for class HistoryRecord.", nameof(instanceId));

            if (!nodeId.IsSet)
                throw new ArgumentException("Property is required for class HistoryRecord.", nameof(nodeId));

            if (!nodeName.IsSet)
                throw new ArgumentException("Property is required for class HistoryRecord.", nameof(nodeName));

            if (!nodeType.IsSet)
                throw new ArgumentException("Property is required for class HistoryRecord.", nameof(nodeType));

            if (!action.IsSet)
                throw new ArgumentException("Property is required for class HistoryRecord.", nameof(action));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class HistoryRecord.", nameof(timestamp));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class HistoryRecord.");

            if (instanceId.IsSet && instanceId.Value == null)
                throw new ArgumentNullException(nameof(instanceId), "Property is not nullable for class HistoryRecord.");

            if (nodeId.IsSet && nodeId.Value == null)
                throw new ArgumentNullException(nameof(nodeId), "Property is not nullable for class HistoryRecord.");

            if (nodeName.IsSet && nodeName.Value == null)
                throw new ArgumentNullException(nameof(nodeName), "Property is not nullable for class HistoryRecord.");

            if (nodeType.IsSet && nodeType.Value == null)
                throw new ArgumentNullException(nameof(nodeType), "Property is not nullable for class HistoryRecord.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class HistoryRecord.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class HistoryRecord.");

            if (variables.IsSet && variables.Value == null)
                throw new ArgumentNullException(nameof(variables), "Property is not nullable for class HistoryRecord.");

            return new HistoryRecord(id.Value!.Value!, instanceId.Value!.Value!, nodeId.Value!, nodeName.Value!, nodeType.Value!, action.Value!, timestamp.Value!.Value!, variables);
        }

        /// <summary>
        /// Serializes a <see cref="HistoryRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="historyRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HistoryRecord historyRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, historyRecord, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HistoryRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="historyRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HistoryRecord historyRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            if (historyRecord.NodeId == null)
                throw new ArgumentNullException(nameof(historyRecord.NodeId), "Property is required for class HistoryRecord.");

            if (historyRecord.NodeName == null)
                throw new ArgumentNullException(nameof(historyRecord.NodeName), "Property is required for class HistoryRecord.");

            if (historyRecord.NodeType == null)
                throw new ArgumentNullException(nameof(historyRecord.NodeType), "Property is required for class HistoryRecord.");

            if (historyRecord.Action == null)
                throw new ArgumentNullException(nameof(historyRecord.Action), "Property is required for class HistoryRecord.");

            if (historyRecord.VariablesOption.IsSet && historyRecord.Variables == null)
                throw new ArgumentNullException(nameof(historyRecord.Variables), "Property is required for class HistoryRecord.");

            writer.WriteString("id", historyRecord.Id);

            writer.WriteString("instance_id", historyRecord.InstanceId);

            writer.WriteString("node_id", historyRecord.NodeId);

            writer.WriteString("node_name", historyRecord.NodeName);

            writer.WriteString("node_type", historyRecord.NodeType);

            writer.WriteString("action", historyRecord.Action);

            writer.WriteString("timestamp", historyRecord.Timestamp.ToString(TimestampFormat));

            if (historyRecord.VariablesOption.IsSet)
            {
                writer.WritePropertyName("variables");
                JsonSerializer.Serialize(writer, historyRecord.Variables, jsonSerializerOptions);
            }
        }
    }
}
