// <auto-generated>
/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using NativeBPM.Client.Client;

namespace NativeBPM.Client.Model
{
    /// <summary>
    /// OutVariable
    /// </summary>
    public partial class OutVariable : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OutVariable" /> class.
        /// </summary>
        /// <param name="source">source</param>
        /// <param name="target">target</param>
        /// <param name="variables">variables</param>
        [JsonConstructor]
        public OutVariable(Option<string?> source = default, Option<string?> target = default, Option<string?> variables = default)
        {
            SourceOption = source;
            TargetOption = target;
            VariablesOption = variables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public string? Source { get { return this.SourceOption.Value; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Target
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TargetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        [JsonPropertyName("target")]
        public string? Target { get { return this.TargetOption.Value; } set { this.TargetOption = new(value); } }

        /// <summary>
        /// Used to track the state of Variables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VariablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Variables
        /// </summary>
        [JsonPropertyName("variables")]
        public string? Variables { get { return this.VariablesOption.Value; } set { this.VariablesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OutVariable {\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OutVariable" />
    /// </summary>
    public partial class OutVariableJsonConverter : JsonConverter<OutVariable>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="OutVariableJsonConverter" /> class.
        /// </summary>
        public OutVariableJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="OutVariable" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OutVariable Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> source = default;
            Option<string?> target = default;
            Option<string?> variables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "target":
                            target = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "variables":
                            variables = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class OutVariable.");

            if (target.IsSet && target.Value == null)
                throw new ArgumentNullException(nameof(target), "Property is not nullable for class OutVariable.");

            if (variables.IsSet && variables.Value == null)
                throw new ArgumentNullException(nameof(variables), "Property is not nullable for class OutVariable.");

            return new OutVariable(source, target, variables);
        }

        /// <summary>
        /// Serializes a <see cref="OutVariable" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="outVariable"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OutVariable outVariable, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, outVariable, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OutVariable" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="outVariable"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OutVariable outVariable, JsonSerializerOptions jsonSerializerOptions)
        {
            if (outVariable.SourceOption.IsSet && outVariable.Source == null)
                throw new ArgumentNullException(nameof(outVariable.Source), "Property is required for class OutVariable.");

            if (outVariable.TargetOption.IsSet && outVariable.Target == null)
                throw new ArgumentNullException(nameof(outVariable.Target), "Property is required for class OutVariable.");

            if (outVariable.VariablesOption.IsSet && outVariable.Variables == null)
                throw new ArgumentNullException(nameof(outVariable.Variables), "Property is required for class OutVariable.");

            if (outVariable.SourceOption.IsSet)
                writer.WriteString("source", outVariable.Source);

            if (outVariable.TargetOption.IsSet)
                writer.WriteString("target", outVariable.Target);

            if (outVariable.VariablesOption.IsSet)
                writer.WriteString("variables", outVariable.Variables);
        }
    }
}
