// <auto-generated>
/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using NativeBPM.Client.Client;

namespace NativeBPM.Client.Model
{
    /// <summary>
    /// TaskRecord
    /// </summary>
    public partial class TaskRecord : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskRecord" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="instanceId">instanceId</param>
        /// <param name="activityId">activityId</param>
        /// <param name="name">name</param>
        /// <param name="assignee">assignee</param>
        /// <param name="candidateGroups">candidateGroups</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="dueDate">dueDate</param>
        /// <param name="inputSchema">JSON schema definition of form widgets</param>
        /// <param name="claimedAt">claimedAt</param>
        /// <param name="completedAt">completedAt</param>
        /// <param name="currentStep">currentStep</param>
        /// <param name="draftVariables">draftVariables</param>
        [JsonConstructor]
        public TaskRecord(Guid id, Guid instanceId, string activityId, string name, string assignee, string candidateGroups, string status, DateTime createdAt, Option<DateTime?> dueDate = default, Option<string?> inputSchema = default, Option<DateTime?> claimedAt = default, Option<DateTime?> completedAt = default, Option<int?> currentStep = default, Option<Dictionary<string, Object>?> draftVariables = default)
        {
            Id = id;
            InstanceId = instanceId;
            ActivityId = activityId;
            Name = name;
            Assignee = assignee;
            CandidateGroups = candidateGroups;
            Status = status;
            CreatedAt = createdAt;
            DueDateOption = dueDate;
            InputSchemaOption = inputSchema;
            ClaimedAtOption = claimedAt;
            CompletedAtOption = completedAt;
            CurrentStepOption = currentStep;
            DraftVariablesOption = draftVariables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets InstanceId
        /// </summary>
        [JsonPropertyName("instance_id")]
        public Guid InstanceId { get; set; }

        /// <summary>
        /// Gets or Sets ActivityId
        /// </summary>
        [JsonPropertyName("activity_id")]
        public string ActivityId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Assignee
        /// </summary>
        [JsonPropertyName("assignee")]
        public string Assignee { get; set; }

        /// <summary>
        /// Gets or Sets CandidateGroups
        /// </summary>
        [JsonPropertyName("candidate_groups")]
        public string CandidateGroups { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /* <example>CREATED</example> */
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of DueDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DueDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets DueDate
        /// </summary>
        [JsonPropertyName("due_date")]
        public DateTime? DueDate { get { return this.DueDateOption.Value; } set { this.DueDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of InputSchema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InputSchemaOption { get; private set; }

        /// <summary>
        /// JSON schema definition of form widgets
        /// </summary>
        /// <value>JSON schema definition of form widgets</value>
        [JsonPropertyName("input_schema")]
        public string? InputSchema { get { return this.InputSchemaOption.Value; } set { this.InputSchemaOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClaimedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ClaimedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ClaimedAt
        /// </summary>
        [JsonPropertyName("claimed_at")]
        public DateTime? ClaimedAt { get { return this.ClaimedAtOption.Value; } set { this.ClaimedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completed_at")]
        public DateTime? CompletedAt { get { return this.CompletedAtOption.Value; } set { this.CompletedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of CurrentStep
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CurrentStepOption { get; private set; }

        /// <summary>
        /// Gets or Sets CurrentStep
        /// </summary>
        [JsonPropertyName("current_step")]
        public int? CurrentStep { get { return this.CurrentStepOption.Value; } set { this.CurrentStepOption = new(value); } }

        /// <summary>
        /// Used to track the state of DraftVariables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> DraftVariablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets DraftVariables
        /// </summary>
        [JsonPropertyName("draft_variables")]
        public Dictionary<string, Object>? DraftVariables { get { return this.DraftVariablesOption.Value; } set { this.DraftVariablesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskRecord {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  ActivityId: ").Append(ActivityId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Assignee: ").Append(Assignee).Append("\n");
            sb.Append("  CandidateGroups: ").Append(CandidateGroups).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  InputSchema: ").Append(InputSchema).Append("\n");
            sb.Append("  ClaimedAt: ").Append(ClaimedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  CurrentStep: ").Append(CurrentStep).Append("\n");
            sb.Append("  DraftVariables: ").Append(DraftVariables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TaskRecord" />
    /// </summary>
    public class TaskRecordJsonConverter : JsonConverter<TaskRecord>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DueDate
        /// </summary>
        public static string DueDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ClaimedAt
        /// </summary>
        public static string ClaimedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public static string CompletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TaskRecord" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TaskRecord Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> instanceId = default;
            Option<string?> activityId = default;
            Option<string?> name = default;
            Option<string?> assignee = default;
            Option<string?> candidateGroups = default;
            Option<string?> status = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> dueDate = default;
            Option<string?> inputSchema = default;
            Option<DateTime?> claimedAt = default;
            Option<DateTime?> completedAt = default;
            Option<int?> currentStep = default;
            Option<Dictionary<string, Object>?> draftVariables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "instance_id":
                            instanceId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "activity_id":
                            activityId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assignee":
                            assignee = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "candidate_groups":
                            candidateGroups = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "due_date":
                            dueDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "input_schema":
                            inputSchema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "claimed_at":
                            claimedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "completed_at":
                            completedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "current_step":
                            currentStep = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "draft_variables":
                            draftVariables = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(id));

            if (!instanceId.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(instanceId));

            if (!activityId.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(activityId));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(name));

            if (!assignee.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(assignee));

            if (!candidateGroups.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(candidateGroups));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class TaskRecord.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class TaskRecord.");

            if (instanceId.IsSet && instanceId.Value == null)
                throw new ArgumentNullException(nameof(instanceId), "Property is not nullable for class TaskRecord.");

            if (activityId.IsSet && activityId.Value == null)
                throw new ArgumentNullException(nameof(activityId), "Property is not nullable for class TaskRecord.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class TaskRecord.");

            if (assignee.IsSet && assignee.Value == null)
                throw new ArgumentNullException(nameof(assignee), "Property is not nullable for class TaskRecord.");

            if (candidateGroups.IsSet && candidateGroups.Value == null)
                throw new ArgumentNullException(nameof(candidateGroups), "Property is not nullable for class TaskRecord.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class TaskRecord.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class TaskRecord.");

            if (dueDate.IsSet && dueDate.Value == null)
                throw new ArgumentNullException(nameof(dueDate), "Property is not nullable for class TaskRecord.");

            if (inputSchema.IsSet && inputSchema.Value == null)
                throw new ArgumentNullException(nameof(inputSchema), "Property is not nullable for class TaskRecord.");

            if (claimedAt.IsSet && claimedAt.Value == null)
                throw new ArgumentNullException(nameof(claimedAt), "Property is not nullable for class TaskRecord.");

            if (completedAt.IsSet && completedAt.Value == null)
                throw new ArgumentNullException(nameof(completedAt), "Property is not nullable for class TaskRecord.");

            if (currentStep.IsSet && currentStep.Value == null)
                throw new ArgumentNullException(nameof(currentStep), "Property is not nullable for class TaskRecord.");

            if (draftVariables.IsSet && draftVariables.Value == null)
                throw new ArgumentNullException(nameof(draftVariables), "Property is not nullable for class TaskRecord.");

            return new TaskRecord(id.Value!.Value!, instanceId.Value!.Value!, activityId.Value!, name.Value!, assignee.Value!, candidateGroups.Value!, status.Value!, createdAt.Value!.Value!, dueDate, inputSchema, claimedAt, completedAt, currentStep, draftVariables);
        }

        /// <summary>
        /// Serializes a <see cref="TaskRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="taskRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TaskRecord taskRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, taskRecord, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TaskRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="taskRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TaskRecord taskRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            if (taskRecord.ActivityId == null)
                throw new ArgumentNullException(nameof(taskRecord.ActivityId), "Property is required for class TaskRecord.");

            if (taskRecord.Name == null)
                throw new ArgumentNullException(nameof(taskRecord.Name), "Property is required for class TaskRecord.");

            if (taskRecord.Assignee == null)
                throw new ArgumentNullException(nameof(taskRecord.Assignee), "Property is required for class TaskRecord.");

            if (taskRecord.CandidateGroups == null)
                throw new ArgumentNullException(nameof(taskRecord.CandidateGroups), "Property is required for class TaskRecord.");

            if (taskRecord.Status == null)
                throw new ArgumentNullException(nameof(taskRecord.Status), "Property is required for class TaskRecord.");

            if (taskRecord.InputSchemaOption.IsSet && taskRecord.InputSchema == null)
                throw new ArgumentNullException(nameof(taskRecord.InputSchema), "Property is required for class TaskRecord.");

            if (taskRecord.DraftVariablesOption.IsSet && taskRecord.DraftVariables == null)
                throw new ArgumentNullException(nameof(taskRecord.DraftVariables), "Property is required for class TaskRecord.");

            writer.WriteString("id", taskRecord.Id);

            writer.WriteString("instance_id", taskRecord.InstanceId);

            writer.WriteString("activity_id", taskRecord.ActivityId);

            writer.WriteString("name", taskRecord.Name);

            writer.WriteString("assignee", taskRecord.Assignee);

            writer.WriteString("candidate_groups", taskRecord.CandidateGroups);

            writer.WriteString("status", taskRecord.Status);

            writer.WriteString("created_at", taskRecord.CreatedAt.ToString(CreatedAtFormat));

            if (taskRecord.DueDateOption.IsSet)
                writer.WriteString("due_date", taskRecord.DueDateOption.Value!.Value.ToString(DueDateFormat));

            if (taskRecord.InputSchemaOption.IsSet)
                writer.WriteString("input_schema", taskRecord.InputSchema);

            if (taskRecord.ClaimedAtOption.IsSet)
                writer.WriteString("claimed_at", taskRecord.ClaimedAtOption.Value!.Value.ToString(ClaimedAtFormat));

            if (taskRecord.CompletedAtOption.IsSet)
                writer.WriteString("completed_at", taskRecord.CompletedAtOption.Value!.Value.ToString(CompletedAtFormat));

            if (taskRecord.CurrentStepOption.IsSet)
                writer.WriteNumber("current_step", taskRecord.CurrentStepOption.Value!.Value);

            if (taskRecord.DraftVariablesOption.IsSet)
            {
                writer.WritePropertyName("draft_variables");
                JsonSerializer.Serialize(writer, taskRecord.DraftVariables, jsonSerializerOptions);
            }
        }
    }
}
