/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NativeBPM.Client.Model;
using NativeBPM.Client.Client;
using System.Reflection;

namespace NativeBPM.Client.Test.Model
{
    /// <summary>
    ///  Class for testing NodeAST
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeASTTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeAST
        //private NodeAST instance;

        public NodeASTTests()
        {
            // TODO uncomment below to create an instance of NodeAST
            //instance = new NodeAST();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeAST
        /// </summary>
        [Fact]
        public void NodeASTInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeAST
            //Assert.IsType<NodeAST>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Topic'
        /// </summary>
        [Fact]
        public void TopicTest()
        {
            // TODO unit test for the property 'Topic'
        }

        /// <summary>
        /// Test the property 'WasmPath'
        /// </summary>
        [Fact]
        public void WasmPathTest()
        {
            // TODO unit test for the property 'WasmPath'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }

        /// <summary>
        /// Test the property 'SystemInstruction'
        /// </summary>
        [Fact]
        public void SystemInstructionTest()
        {
            // TODO unit test for the property 'SystemInstruction'
        }

        /// <summary>
        /// Test the property 'ResponseSchema'
        /// </summary>
        [Fact]
        public void ResponseSchemaTest()
        {
            // TODO unit test for the property 'ResponseSchema'
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'ResultVar'
        /// </summary>
        [Fact]
        public void ResultVarTest()
        {
            // TODO unit test for the property 'ResultVar'
        }

        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Fact]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }

        /// <summary>
        /// Test the property 'CandidateGroups'
        /// </summary>
        [Fact]
        public void CandidateGroupsTest()
        {
            // TODO unit test for the property 'CandidateGroups'
        }

        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }

        /// <summary>
        /// Test the property 'InputSchema'
        /// </summary>
        [Fact]
        public void InputSchemaTest()
        {
            // TODO unit test for the property 'InputSchema'
        }

        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Fact]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }

        /// <summary>
        /// Test the property 'FormKey'
        /// </summary>
        [Fact]
        public void FormKeyTest()
        {
            // TODO unit test for the property 'FormKey'
        }

        /// <summary>
        /// Test the property 'CalledElement'
        /// </summary>
        [Fact]
        public void CalledElementTest()
        {
            // TODO unit test for the property 'CalledElement'
        }

        /// <summary>
        /// Test the property 'InVariables'
        /// </summary>
        [Fact]
        public void InVariablesTest()
        {
            // TODO unit test for the property 'InVariables'
        }

        /// <summary>
        /// Test the property 'OutVariables'
        /// </summary>
        [Fact]
        public void OutVariablesTest()
        {
            // TODO unit test for the property 'OutVariables'
        }

        /// <summary>
        /// Test the property 'DecisionRef'
        /// </summary>
        [Fact]
        public void DecisionRefTest()
        {
            // TODO unit test for the property 'DecisionRef'
        }

        /// <summary>
        /// Test the property 'MapDecisionResult'
        /// </summary>
        [Fact]
        public void MapDecisionResultTest()
        {
            // TODO unit test for the property 'MapDecisionResult'
        }

        /// <summary>
        /// Test the property 'HitPolicy'
        /// </summary>
        [Fact]
        public void HitPolicyTest()
        {
            // TODO unit test for the property 'HitPolicy'
        }

        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Fact]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }

        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Fact]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }

        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Fact]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }

        /// <summary>
        /// Test the property 'AttachedToRef'
        /// </summary>
        [Fact]
        public void AttachedToRefTest()
        {
            // TODO unit test for the property 'AttachedToRef'
        }

        /// <summary>
        /// Test the property 'TimeDuration'
        /// </summary>
        [Fact]
        public void TimeDurationTest()
        {
            // TODO unit test for the property 'TimeDuration'
        }

        /// <summary>
        /// Test the property 'TimeDate'
        /// </summary>
        [Fact]
        public void TimeDateTest()
        {
            // TODO unit test for the property 'TimeDate'
        }

        /// <summary>
        /// Test the property 'TimeCycle'
        /// </summary>
        [Fact]
        public void TimeCycleTest()
        {
            // TODO unit test for the property 'TimeCycle'
        }

        /// <summary>
        /// Test the property 'CancelActivity'
        /// </summary>
        [Fact]
        public void CancelActivityTest()
        {
            // TODO unit test for the property 'CancelActivity'
        }
    }
}
