/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NativeBPM.Client.Model;
using NativeBPM.Client.Client;
using System.Reflection;

namespace NativeBPM.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OutVariable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutVariableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutVariable
        //private OutVariable instance;

        public OutVariableTests()
        {
            // TODO uncomment below to create an instance of OutVariable
            //instance = new OutVariable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutVariable
        /// </summary>
        [Fact]
        public void OutVariableInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutVariable
            //Assert.IsType<OutVariable>(instance);
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
    }
}
