/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NativeBPM.Client.Model;
using NativeBPM.Client.Client;
using System.Reflection;

namespace NativeBPM.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StartInstanceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StartInstanceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StartInstanceRequest
        //private StartInstanceRequest instance;

        public StartInstanceRequestTests()
        {
            // TODO uncomment below to create an instance of StartInstanceRequest
            //instance = new StartInstanceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StartInstanceRequest
        /// </summary>
        [Fact]
        public void StartInstanceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" StartInstanceRequest
            //Assert.IsType<StartInstanceRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Fact]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }

        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
    }
}
