/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NativeBPM.Client.Model;
using NativeBPM.Client.Client;
using System.Reflection;

namespace NativeBPM.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TaskRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskRecordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskRecord
        //private TaskRecord instance;

        public TaskRecordTests()
        {
            // TODO uncomment below to create an instance of TaskRecord
            //instance = new TaskRecord();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskRecord
        /// </summary>
        [Fact]
        public void TaskRecordInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskRecord
            //Assert.IsType<TaskRecord>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Fact]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Fact]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }

        /// <summary>
        /// Test the property 'CandidateGroups'
        /// </summary>
        [Fact]
        public void CandidateGroupsTest()
        {
            // TODO unit test for the property 'CandidateGroups'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }

        /// <summary>
        /// Test the property 'InputSchema'
        /// </summary>
        [Fact]
        public void InputSchemaTest()
        {
            // TODO unit test for the property 'InputSchema'
        }

        /// <summary>
        /// Test the property 'ClaimedAt'
        /// </summary>
        [Fact]
        public void ClaimedAtTest()
        {
            // TODO unit test for the property 'ClaimedAt'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'CurrentStep'
        /// </summary>
        [Fact]
        public void CurrentStepTest()
        {
            // TODO unit test for the property 'CurrentStep'
        }

        /// <summary>
        /// Test the property 'DraftVariables'
        /// </summary>
        [Fact]
        public void DraftVariablesTest()
        {
            // TODO unit test for the property 'DraftVariables'
        }
    }
}
