/*
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nativebpm.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nativebpm.client.model.DMNInputAST;
import com.nativebpm.client.model.DMNOutputAST;
import com.nativebpm.client.model.DMNRuleAST;
import com.nativebpm.client.model.InVariable;
import com.nativebpm.client.model.OutVariable;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.nativebpm.client.JSON;

/**
 * NodeAST
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class NodeAST {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    START_EVENT("startEvent"),
    
    END_EVENT("endEvent"),
    
    SERVICE_TASK("serviceTask"),
    
    USER_TASK("userTask"),
    
    AI_SERVICE_TASK("aiServiceTask"),
    
    AI_TASK("aiTask"),
    
    EXCLUSIVE_GATEWAY("exclusiveGateway"),
    
    PARALLEL_GATEWAY("parallelGateway"),
    
    EVENT_BASED_GATEWAY("eventBasedGateway"),
    
    CALL_ACTIVITY("callActivity"),
    
    BUSINESS_RULE_TASK("businessRuleTask"),
    
    BOUNDARY_TIMER_EVENT("boundaryTimerEvent");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String SERIALIZED_NAME_TOPIC = "topic";
  @SerializedName(SERIALIZED_NAME_TOPIC)
  @javax.annotation.Nullable
  private String topic;

  public static final String SERIALIZED_NAME_WASM_PATH = "wasmPath";
  @SerializedName(SERIALIZED_NAME_WASM_PATH)
  @javax.annotation.Nullable
  private String wasmPath;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nullable
  private String provider;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nullable
  private String model;

  public static final String SERIALIZED_NAME_PROMPT = "prompt";
  @SerializedName(SERIALIZED_NAME_PROMPT)
  @javax.annotation.Nullable
  private String prompt;

  public static final String SERIALIZED_NAME_SYSTEM_INSTRUCTION = "systemInstruction";
  @SerializedName(SERIALIZED_NAME_SYSTEM_INSTRUCTION)
  @javax.annotation.Nullable
  private String systemInstruction;

  public static final String SERIALIZED_NAME_RESPONSE_SCHEMA = "responseSchema";
  @SerializedName(SERIALIZED_NAME_RESPONSE_SCHEMA)
  @javax.annotation.Nullable
  private String responseSchema;

  public static final String SERIALIZED_NAME_TEMPERATURE = "temperature";
  @SerializedName(SERIALIZED_NAME_TEMPERATURE)
  @javax.annotation.Nullable
  private BigDecimal temperature;

  public static final String SERIALIZED_NAME_RESULT_VAR = "resultVar";
  @SerializedName(SERIALIZED_NAME_RESULT_VAR)
  @javax.annotation.Nullable
  private String resultVar;

  public static final String SERIALIZED_NAME_ASSIGNEE = "assignee";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE)
  @javax.annotation.Nullable
  private String assignee;

  public static final String SERIALIZED_NAME_CANDIDATE_GROUPS = "candidateGroups";
  @SerializedName(SERIALIZED_NAME_CANDIDATE_GROUPS)
  @javax.annotation.Nullable
  private String candidateGroups;

  public static final String SERIALIZED_NAME_DUE_DATE = "dueDate";
  @SerializedName(SERIALIZED_NAME_DUE_DATE)
  @javax.annotation.Nullable
  private String dueDate;

  public static final String SERIALIZED_NAME_INPUT_SCHEMA = "inputSchema";
  @SerializedName(SERIALIZED_NAME_INPUT_SCHEMA)
  @javax.annotation.Nullable
  private String inputSchema;

  public static final String SERIALIZED_NAME_FORM_ID = "formId";
  @SerializedName(SERIALIZED_NAME_FORM_ID)
  @javax.annotation.Nullable
  private String formId;

  public static final String SERIALIZED_NAME_FORM_KEY = "formKey";
  @SerializedName(SERIALIZED_NAME_FORM_KEY)
  @javax.annotation.Nullable
  private String formKey;

  public static final String SERIALIZED_NAME_CALLED_ELEMENT = "calledElement";
  @SerializedName(SERIALIZED_NAME_CALLED_ELEMENT)
  @javax.annotation.Nullable
  private String calledElement;

  public static final String SERIALIZED_NAME_IN_VARIABLES = "inVariables";
  @SerializedName(SERIALIZED_NAME_IN_VARIABLES)
  @javax.annotation.Nullable
  private List<InVariable> inVariables = new ArrayList<>();

  public static final String SERIALIZED_NAME_OUT_VARIABLES = "outVariables";
  @SerializedName(SERIALIZED_NAME_OUT_VARIABLES)
  @javax.annotation.Nullable
  private List<OutVariable> outVariables = new ArrayList<>();

  public static final String SERIALIZED_NAME_DECISION_REF = "decisionRef";
  @SerializedName(SERIALIZED_NAME_DECISION_REF)
  @javax.annotation.Nullable
  private String decisionRef;

  public static final String SERIALIZED_NAME_MAP_DECISION_RESULT = "mapDecisionResult";
  @SerializedName(SERIALIZED_NAME_MAP_DECISION_RESULT)
  @javax.annotation.Nullable
  private String mapDecisionResult;

  public static final String SERIALIZED_NAME_HIT_POLICY = "hitPolicy";
  @SerializedName(SERIALIZED_NAME_HIT_POLICY)
  @javax.annotation.Nullable
  private String hitPolicy;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  @javax.annotation.Nullable
  private List<DMNInputAST> inputs = new ArrayList<>();

  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  @javax.annotation.Nullable
  private List<DMNOutputAST> outputs = new ArrayList<>();

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  @javax.annotation.Nullable
  private List<DMNRuleAST> rules = new ArrayList<>();

  public static final String SERIALIZED_NAME_ATTACHED_TO_REF = "attachedToRef";
  @SerializedName(SERIALIZED_NAME_ATTACHED_TO_REF)
  @javax.annotation.Nullable
  private String attachedToRef;

  public static final String SERIALIZED_NAME_TIME_DURATION = "timeDuration";
  @SerializedName(SERIALIZED_NAME_TIME_DURATION)
  @javax.annotation.Nullable
  private String timeDuration;

  public static final String SERIALIZED_NAME_TIME_DATE = "timeDate";
  @SerializedName(SERIALIZED_NAME_TIME_DATE)
  @javax.annotation.Nullable
  private String timeDate;

  public static final String SERIALIZED_NAME_TIME_CYCLE = "timeCycle";
  @SerializedName(SERIALIZED_NAME_TIME_CYCLE)
  @javax.annotation.Nullable
  private String timeCycle;

  public static final String SERIALIZED_NAME_CANCEL_ACTIVITY = "cancelActivity";
  @SerializedName(SERIALIZED_NAME_CANCEL_ACTIVITY)
  @javax.annotation.Nullable
  private Boolean cancelActivity;

  public NodeAST() {
  }

  public NodeAST id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public NodeAST name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public NodeAST type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public NodeAST topic(@javax.annotation.Nullable String topic) {
    this.topic = topic;
    return this;
  }

  /**
   * Get topic
   * @return topic
   */
  @javax.annotation.Nullable
  public String getTopic() {
    return topic;
  }

  public void setTopic(@javax.annotation.Nullable String topic) {
    this.topic = topic;
  }


  public NodeAST wasmPath(@javax.annotation.Nullable String wasmPath) {
    this.wasmPath = wasmPath;
    return this;
  }

  /**
   * Get wasmPath
   * @return wasmPath
   */
  @javax.annotation.Nullable
  public String getWasmPath() {
    return wasmPath;
  }

  public void setWasmPath(@javax.annotation.Nullable String wasmPath) {
    this.wasmPath = wasmPath;
  }


  public NodeAST provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  public String getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public NodeAST model(@javax.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  public String getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }


  public NodeAST prompt(@javax.annotation.Nullable String prompt) {
    this.prompt = prompt;
    return this;
  }

  /**
   * Get prompt
   * @return prompt
   */
  @javax.annotation.Nullable
  public String getPrompt() {
    return prompt;
  }

  public void setPrompt(@javax.annotation.Nullable String prompt) {
    this.prompt = prompt;
  }


  public NodeAST systemInstruction(@javax.annotation.Nullable String systemInstruction) {
    this.systemInstruction = systemInstruction;
    return this;
  }

  /**
   * Get systemInstruction
   * @return systemInstruction
   */
  @javax.annotation.Nullable
  public String getSystemInstruction() {
    return systemInstruction;
  }

  public void setSystemInstruction(@javax.annotation.Nullable String systemInstruction) {
    this.systemInstruction = systemInstruction;
  }


  public NodeAST responseSchema(@javax.annotation.Nullable String responseSchema) {
    this.responseSchema = responseSchema;
    return this;
  }

  /**
   * Get responseSchema
   * @return responseSchema
   */
  @javax.annotation.Nullable
  public String getResponseSchema() {
    return responseSchema;
  }

  public void setResponseSchema(@javax.annotation.Nullable String responseSchema) {
    this.responseSchema = responseSchema;
  }


  public NodeAST temperature(@javax.annotation.Nullable BigDecimal temperature) {
    this.temperature = temperature;
    return this;
  }

  /**
   * Get temperature
   * @return temperature
   */
  @javax.annotation.Nullable
  public BigDecimal getTemperature() {
    return temperature;
  }

  public void setTemperature(@javax.annotation.Nullable BigDecimal temperature) {
    this.temperature = temperature;
  }


  public NodeAST resultVar(@javax.annotation.Nullable String resultVar) {
    this.resultVar = resultVar;
    return this;
  }

  /**
   * Get resultVar
   * @return resultVar
   */
  @javax.annotation.Nullable
  public String getResultVar() {
    return resultVar;
  }

  public void setResultVar(@javax.annotation.Nullable String resultVar) {
    this.resultVar = resultVar;
  }


  public NodeAST assignee(@javax.annotation.Nullable String assignee) {
    this.assignee = assignee;
    return this;
  }

  /**
   * Get assignee
   * @return assignee
   */
  @javax.annotation.Nullable
  public String getAssignee() {
    return assignee;
  }

  public void setAssignee(@javax.annotation.Nullable String assignee) {
    this.assignee = assignee;
  }


  public NodeAST candidateGroups(@javax.annotation.Nullable String candidateGroups) {
    this.candidateGroups = candidateGroups;
    return this;
  }

  /**
   * Get candidateGroups
   * @return candidateGroups
   */
  @javax.annotation.Nullable
  public String getCandidateGroups() {
    return candidateGroups;
  }

  public void setCandidateGroups(@javax.annotation.Nullable String candidateGroups) {
    this.candidateGroups = candidateGroups;
  }


  public NodeAST dueDate(@javax.annotation.Nullable String dueDate) {
    this.dueDate = dueDate;
    return this;
  }

  /**
   * Get dueDate
   * @return dueDate
   */
  @javax.annotation.Nullable
  public String getDueDate() {
    return dueDate;
  }

  public void setDueDate(@javax.annotation.Nullable String dueDate) {
    this.dueDate = dueDate;
  }


  public NodeAST inputSchema(@javax.annotation.Nullable String inputSchema) {
    this.inputSchema = inputSchema;
    return this;
  }

  /**
   * Get inputSchema
   * @return inputSchema
   */
  @javax.annotation.Nullable
  public String getInputSchema() {
    return inputSchema;
  }

  public void setInputSchema(@javax.annotation.Nullable String inputSchema) {
    this.inputSchema = inputSchema;
  }


  public NodeAST formId(@javax.annotation.Nullable String formId) {
    this.formId = formId;
    return this;
  }

  /**
   * Get formId
   * @return formId
   */
  @javax.annotation.Nullable
  public String getFormId() {
    return formId;
  }

  public void setFormId(@javax.annotation.Nullable String formId) {
    this.formId = formId;
  }


  public NodeAST formKey(@javax.annotation.Nullable String formKey) {
    this.formKey = formKey;
    return this;
  }

  /**
   * Get formKey
   * @return formKey
   */
  @javax.annotation.Nullable
  public String getFormKey() {
    return formKey;
  }

  public void setFormKey(@javax.annotation.Nullable String formKey) {
    this.formKey = formKey;
  }


  public NodeAST calledElement(@javax.annotation.Nullable String calledElement) {
    this.calledElement = calledElement;
    return this;
  }

  /**
   * Get calledElement
   * @return calledElement
   */
  @javax.annotation.Nullable
  public String getCalledElement() {
    return calledElement;
  }

  public void setCalledElement(@javax.annotation.Nullable String calledElement) {
    this.calledElement = calledElement;
  }


  public NodeAST inVariables(@javax.annotation.Nullable List<InVariable> inVariables) {
    this.inVariables = inVariables;
    return this;
  }

  public NodeAST addInVariablesItem(InVariable inVariablesItem) {
    if (this.inVariables == null) {
      this.inVariables = new ArrayList<>();
    }
    this.inVariables.add(inVariablesItem);
    return this;
  }

  /**
   * Get inVariables
   * @return inVariables
   */
  @javax.annotation.Nullable
  public List<InVariable> getInVariables() {
    return inVariables;
  }

  public void setInVariables(@javax.annotation.Nullable List<InVariable> inVariables) {
    this.inVariables = inVariables;
  }


  public NodeAST outVariables(@javax.annotation.Nullable List<OutVariable> outVariables) {
    this.outVariables = outVariables;
    return this;
  }

  public NodeAST addOutVariablesItem(OutVariable outVariablesItem) {
    if (this.outVariables == null) {
      this.outVariables = new ArrayList<>();
    }
    this.outVariables.add(outVariablesItem);
    return this;
  }

  /**
   * Get outVariables
   * @return outVariables
   */
  @javax.annotation.Nullable
  public List<OutVariable> getOutVariables() {
    return outVariables;
  }

  public void setOutVariables(@javax.annotation.Nullable List<OutVariable> outVariables) {
    this.outVariables = outVariables;
  }


  public NodeAST decisionRef(@javax.annotation.Nullable String decisionRef) {
    this.decisionRef = decisionRef;
    return this;
  }

  /**
   * Get decisionRef
   * @return decisionRef
   */
  @javax.annotation.Nullable
  public String getDecisionRef() {
    return decisionRef;
  }

  public void setDecisionRef(@javax.annotation.Nullable String decisionRef) {
    this.decisionRef = decisionRef;
  }


  public NodeAST mapDecisionResult(@javax.annotation.Nullable String mapDecisionResult) {
    this.mapDecisionResult = mapDecisionResult;
    return this;
  }

  /**
   * Get mapDecisionResult
   * @return mapDecisionResult
   */
  @javax.annotation.Nullable
  public String getMapDecisionResult() {
    return mapDecisionResult;
  }

  public void setMapDecisionResult(@javax.annotation.Nullable String mapDecisionResult) {
    this.mapDecisionResult = mapDecisionResult;
  }


  public NodeAST hitPolicy(@javax.annotation.Nullable String hitPolicy) {
    this.hitPolicy = hitPolicy;
    return this;
  }

  /**
   * Get hitPolicy
   * @return hitPolicy
   */
  @javax.annotation.Nullable
  public String getHitPolicy() {
    return hitPolicy;
  }

  public void setHitPolicy(@javax.annotation.Nullable String hitPolicy) {
    this.hitPolicy = hitPolicy;
  }


  public NodeAST inputs(@javax.annotation.Nullable List<DMNInputAST> inputs) {
    this.inputs = inputs;
    return this;
  }

  public NodeAST addInputsItem(DMNInputAST inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

  /**
   * Get inputs
   * @return inputs
   */
  @javax.annotation.Nullable
  public List<DMNInputAST> getInputs() {
    return inputs;
  }

  public void setInputs(@javax.annotation.Nullable List<DMNInputAST> inputs) {
    this.inputs = inputs;
  }


  public NodeAST outputs(@javax.annotation.Nullable List<DMNOutputAST> outputs) {
    this.outputs = outputs;
    return this;
  }

  public NodeAST addOutputsItem(DMNOutputAST outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

  /**
   * Get outputs
   * @return outputs
   */
  @javax.annotation.Nullable
  public List<DMNOutputAST> getOutputs() {
    return outputs;
  }

  public void setOutputs(@javax.annotation.Nullable List<DMNOutputAST> outputs) {
    this.outputs = outputs;
  }


  public NodeAST rules(@javax.annotation.Nullable List<DMNRuleAST> rules) {
    this.rules = rules;
    return this;
  }

  public NodeAST addRulesItem(DMNRuleAST rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Get rules
   * @return rules
   */
  @javax.annotation.Nullable
  public List<DMNRuleAST> getRules() {
    return rules;
  }

  public void setRules(@javax.annotation.Nullable List<DMNRuleAST> rules) {
    this.rules = rules;
  }


  public NodeAST attachedToRef(@javax.annotation.Nullable String attachedToRef) {
    this.attachedToRef = attachedToRef;
    return this;
  }

  /**
   * Get attachedToRef
   * @return attachedToRef
   */
  @javax.annotation.Nullable
  public String getAttachedToRef() {
    return attachedToRef;
  }

  public void setAttachedToRef(@javax.annotation.Nullable String attachedToRef) {
    this.attachedToRef = attachedToRef;
  }


  public NodeAST timeDuration(@javax.annotation.Nullable String timeDuration) {
    this.timeDuration = timeDuration;
    return this;
  }

  /**
   * Get timeDuration
   * @return timeDuration
   */
  @javax.annotation.Nullable
  public String getTimeDuration() {
    return timeDuration;
  }

  public void setTimeDuration(@javax.annotation.Nullable String timeDuration) {
    this.timeDuration = timeDuration;
  }


  public NodeAST timeDate(@javax.annotation.Nullable String timeDate) {
    this.timeDate = timeDate;
    return this;
  }

  /**
   * Get timeDate
   * @return timeDate
   */
  @javax.annotation.Nullable
  public String getTimeDate() {
    return timeDate;
  }

  public void setTimeDate(@javax.annotation.Nullable String timeDate) {
    this.timeDate = timeDate;
  }


  public NodeAST timeCycle(@javax.annotation.Nullable String timeCycle) {
    this.timeCycle = timeCycle;
    return this;
  }

  /**
   * Get timeCycle
   * @return timeCycle
   */
  @javax.annotation.Nullable
  public String getTimeCycle() {
    return timeCycle;
  }

  public void setTimeCycle(@javax.annotation.Nullable String timeCycle) {
    this.timeCycle = timeCycle;
  }


  public NodeAST cancelActivity(@javax.annotation.Nullable Boolean cancelActivity) {
    this.cancelActivity = cancelActivity;
    return this;
  }

  /**
   * Get cancelActivity
   * @return cancelActivity
   */
  @javax.annotation.Nullable
  public Boolean getCancelActivity() {
    return cancelActivity;
  }

  public void setCancelActivity(@javax.annotation.Nullable Boolean cancelActivity) {
    this.cancelActivity = cancelActivity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeAST nodeAST = (NodeAST) o;
    return Objects.equals(this.id, nodeAST.id) &&
        Objects.equals(this.name, nodeAST.name) &&
        Objects.equals(this.type, nodeAST.type) &&
        Objects.equals(this.topic, nodeAST.topic) &&
        Objects.equals(this.wasmPath, nodeAST.wasmPath) &&
        Objects.equals(this.provider, nodeAST.provider) &&
        Objects.equals(this.model, nodeAST.model) &&
        Objects.equals(this.prompt, nodeAST.prompt) &&
        Objects.equals(this.systemInstruction, nodeAST.systemInstruction) &&
        Objects.equals(this.responseSchema, nodeAST.responseSchema) &&
        Objects.equals(this.temperature, nodeAST.temperature) &&
        Objects.equals(this.resultVar, nodeAST.resultVar) &&
        Objects.equals(this.assignee, nodeAST.assignee) &&
        Objects.equals(this.candidateGroups, nodeAST.candidateGroups) &&
        Objects.equals(this.dueDate, nodeAST.dueDate) &&
        Objects.equals(this.inputSchema, nodeAST.inputSchema) &&
        Objects.equals(this.formId, nodeAST.formId) &&
        Objects.equals(this.formKey, nodeAST.formKey) &&
        Objects.equals(this.calledElement, nodeAST.calledElement) &&
        Objects.equals(this.inVariables, nodeAST.inVariables) &&
        Objects.equals(this.outVariables, nodeAST.outVariables) &&
        Objects.equals(this.decisionRef, nodeAST.decisionRef) &&
        Objects.equals(this.mapDecisionResult, nodeAST.mapDecisionResult) &&
        Objects.equals(this.hitPolicy, nodeAST.hitPolicy) &&
        Objects.equals(this.inputs, nodeAST.inputs) &&
        Objects.equals(this.outputs, nodeAST.outputs) &&
        Objects.equals(this.rules, nodeAST.rules) &&
        Objects.equals(this.attachedToRef, nodeAST.attachedToRef) &&
        Objects.equals(this.timeDuration, nodeAST.timeDuration) &&
        Objects.equals(this.timeDate, nodeAST.timeDate) &&
        Objects.equals(this.timeCycle, nodeAST.timeCycle) &&
        Objects.equals(this.cancelActivity, nodeAST.cancelActivity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, topic, wasmPath, provider, model, prompt, systemInstruction, responseSchema, temperature, resultVar, assignee, candidateGroups, dueDate, inputSchema, formId, formKey, calledElement, inVariables, outVariables, decisionRef, mapDecisionResult, hitPolicy, inputs, outputs, rules, attachedToRef, timeDuration, timeDate, timeCycle, cancelActivity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeAST {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    wasmPath: ").append(toIndentedString(wasmPath)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    systemInstruction: ").append(toIndentedString(systemInstruction)).append("\n");
    sb.append("    responseSchema: ").append(toIndentedString(responseSchema)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    resultVar: ").append(toIndentedString(resultVar)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    candidateGroups: ").append(toIndentedString(candidateGroups)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    inputSchema: ").append(toIndentedString(inputSchema)).append("\n");
    sb.append("    formId: ").append(toIndentedString(formId)).append("\n");
    sb.append("    formKey: ").append(toIndentedString(formKey)).append("\n");
    sb.append("    calledElement: ").append(toIndentedString(calledElement)).append("\n");
    sb.append("    inVariables: ").append(toIndentedString(inVariables)).append("\n");
    sb.append("    outVariables: ").append(toIndentedString(outVariables)).append("\n");
    sb.append("    decisionRef: ").append(toIndentedString(decisionRef)).append("\n");
    sb.append("    mapDecisionResult: ").append(toIndentedString(mapDecisionResult)).append("\n");
    sb.append("    hitPolicy: ").append(toIndentedString(hitPolicy)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    attachedToRef: ").append(toIndentedString(attachedToRef)).append("\n");
    sb.append("    timeDuration: ").append(toIndentedString(timeDuration)).append("\n");
    sb.append("    timeDate: ").append(toIndentedString(timeDate)).append("\n");
    sb.append("    timeCycle: ").append(toIndentedString(timeCycle)).append("\n");
    sb.append("    cancelActivity: ").append(toIndentedString(cancelActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "type", "topic", "wasmPath", "provider", "model", "prompt", "systemInstruction", "responseSchema", "temperature", "resultVar", "assignee", "candidateGroups", "dueDate", "inputSchema", "formId", "formKey", "calledElement", "inVariables", "outVariables", "decisionRef", "mapDecisionResult", "hitPolicy", "inputs", "outputs", "rules", "attachedToRef", "timeDuration", "timeDate", "timeCycle", "cancelActivity"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NodeAST
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NodeAST.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in NodeAST is not found in the empty JSON string", NodeAST.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NodeAST.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `NodeAST` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NodeAST.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
      if ((jsonObj.get("topic") != null && !jsonObj.get("topic").isJsonNull()) && !jsonObj.get("topic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `topic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("topic").toString()));
      }
      if ((jsonObj.get("wasmPath") != null && !jsonObj.get("wasmPath").isJsonNull()) && !jsonObj.get("wasmPath").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `wasmPath` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wasmPath").toString()));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      if ((jsonObj.get("prompt") != null && !jsonObj.get("prompt").isJsonNull()) && !jsonObj.get("prompt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `prompt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prompt").toString()));
      }
      if ((jsonObj.get("systemInstruction") != null && !jsonObj.get("systemInstruction").isJsonNull()) && !jsonObj.get("systemInstruction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `systemInstruction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("systemInstruction").toString()));
      }
      if ((jsonObj.get("responseSchema") != null && !jsonObj.get("responseSchema").isJsonNull()) && !jsonObj.get("responseSchema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `responseSchema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("responseSchema").toString()));
      }
      if ((jsonObj.get("resultVar") != null && !jsonObj.get("resultVar").isJsonNull()) && !jsonObj.get("resultVar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `resultVar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resultVar").toString()));
      }
      if ((jsonObj.get("assignee") != null && !jsonObj.get("assignee").isJsonNull()) && !jsonObj.get("assignee").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `assignee` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assignee").toString()));
      }
      if ((jsonObj.get("candidateGroups") != null && !jsonObj.get("candidateGroups").isJsonNull()) && !jsonObj.get("candidateGroups").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `candidateGroups` to be a primitive type in the JSON string but got `%s`", jsonObj.get("candidateGroups").toString()));
      }
      if ((jsonObj.get("dueDate") != null && !jsonObj.get("dueDate").isJsonNull()) && !jsonObj.get("dueDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dueDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dueDate").toString()));
      }
      if ((jsonObj.get("inputSchema") != null && !jsonObj.get("inputSchema").isJsonNull()) && !jsonObj.get("inputSchema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inputSchema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inputSchema").toString()));
      }
      if ((jsonObj.get("formId") != null && !jsonObj.get("formId").isJsonNull()) && !jsonObj.get("formId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `formId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("formId").toString()));
      }
      if ((jsonObj.get("formKey") != null && !jsonObj.get("formKey").isJsonNull()) && !jsonObj.get("formKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `formKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("formKey").toString()));
      }
      if ((jsonObj.get("calledElement") != null && !jsonObj.get("calledElement").isJsonNull()) && !jsonObj.get("calledElement").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `calledElement` to be a primitive type in the JSON string but got `%s`", jsonObj.get("calledElement").toString()));
      }
      if (jsonObj.get("inVariables") != null && !jsonObj.get("inVariables").isJsonNull()) {
        JsonArray jsonArrayinVariables = jsonObj.getAsJsonArray("inVariables");
        if (jsonArrayinVariables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("inVariables").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inVariables` to be an array in the JSON string but got `%s`", jsonObj.get("inVariables").toString()));
          }

          // validate the optional field `inVariables` (array)
          for (int i = 0; i < jsonArrayinVariables.size(); i++) {
            InVariable.validateJsonElement(jsonArrayinVariables.get(i));
          };
        }
      }
      if (jsonObj.get("outVariables") != null && !jsonObj.get("outVariables").isJsonNull()) {
        JsonArray jsonArrayoutVariables = jsonObj.getAsJsonArray("outVariables");
        if (jsonArrayoutVariables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("outVariables").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `outVariables` to be an array in the JSON string but got `%s`", jsonObj.get("outVariables").toString()));
          }

          // validate the optional field `outVariables` (array)
          for (int i = 0; i < jsonArrayoutVariables.size(); i++) {
            OutVariable.validateJsonElement(jsonArrayoutVariables.get(i));
          };
        }
      }
      if ((jsonObj.get("decisionRef") != null && !jsonObj.get("decisionRef").isJsonNull()) && !jsonObj.get("decisionRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `decisionRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("decisionRef").toString()));
      }
      if ((jsonObj.get("mapDecisionResult") != null && !jsonObj.get("mapDecisionResult").isJsonNull()) && !jsonObj.get("mapDecisionResult").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mapDecisionResult` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mapDecisionResult").toString()));
      }
      if ((jsonObj.get("hitPolicy") != null && !jsonObj.get("hitPolicy").isJsonNull()) && !jsonObj.get("hitPolicy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `hitPolicy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hitPolicy").toString()));
      }
      if (jsonObj.get("inputs") != null && !jsonObj.get("inputs").isJsonNull()) {
        JsonArray jsonArrayinputs = jsonObj.getAsJsonArray("inputs");
        if (jsonArrayinputs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("inputs").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inputs` to be an array in the JSON string but got `%s`", jsonObj.get("inputs").toString()));
          }

          // validate the optional field `inputs` (array)
          for (int i = 0; i < jsonArrayinputs.size(); i++) {
            DMNInputAST.validateJsonElement(jsonArrayinputs.get(i));
          };
        }
      }
      if (jsonObj.get("outputs") != null && !jsonObj.get("outputs").isJsonNull()) {
        JsonArray jsonArrayoutputs = jsonObj.getAsJsonArray("outputs");
        if (jsonArrayoutputs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("outputs").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `outputs` to be an array in the JSON string but got `%s`", jsonObj.get("outputs").toString()));
          }

          // validate the optional field `outputs` (array)
          for (int i = 0; i < jsonArrayoutputs.size(); i++) {
            DMNOutputAST.validateJsonElement(jsonArrayoutputs.get(i));
          };
        }
      }
      if (jsonObj.get("rules") != null && !jsonObj.get("rules").isJsonNull()) {
        JsonArray jsonArrayrules = jsonObj.getAsJsonArray("rules");
        if (jsonArrayrules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rules").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rules` to be an array in the JSON string but got `%s`", jsonObj.get("rules").toString()));
          }

          // validate the optional field `rules` (array)
          for (int i = 0; i < jsonArrayrules.size(); i++) {
            DMNRuleAST.validateJsonElement(jsonArrayrules.get(i));
          };
        }
      }
      if ((jsonObj.get("attachedToRef") != null && !jsonObj.get("attachedToRef").isJsonNull()) && !jsonObj.get("attachedToRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `attachedToRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attachedToRef").toString()));
      }
      if ((jsonObj.get("timeDuration") != null && !jsonObj.get("timeDuration").isJsonNull()) && !jsonObj.get("timeDuration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timeDuration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeDuration").toString()));
      }
      if ((jsonObj.get("timeDate") != null && !jsonObj.get("timeDate").isJsonNull()) && !jsonObj.get("timeDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timeDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeDate").toString()));
      }
      if ((jsonObj.get("timeCycle") != null && !jsonObj.get("timeCycle").isJsonNull()) && !jsonObj.get("timeCycle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timeCycle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeCycle").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NodeAST.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NodeAST' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NodeAST> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NodeAST.class));

       return (TypeAdapter<T>) new TypeAdapter<NodeAST>() {
           @Override
           public void write(JsonWriter out, NodeAST value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NodeAST read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NodeAST given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NodeAST
   * @throws IOException if the JSON string is invalid with respect to NodeAST
   */
  public static NodeAST fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NodeAST.class);
  }

  /**
   * Convert an instance of NodeAST to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

