/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.nativebpm.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nativebpm.client.models.ProcessInstance

class ProcessInstanceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProcessInstance
        //val modelInstance = ProcessInstance()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `processId`
        should("test processId") {
            // uncomment below to test the property
            //modelInstance.processId shouldBe ("TODO")
        }

        // to test the property `definitionHash`
        should("test definitionHash") {
            // uncomment below to test the property
            //modelInstance.definitionHash shouldBe ("TODO")
        }

        // to test the property `businessKey`
        should("test businessKey") {
            // uncomment below to test the property
            //modelInstance.businessKey shouldBe ("TODO")
        }

        // to test the property `state` - Base64/raw JSON encoded internal Wazero process engine state representation
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `completed`
        should("test completed") {
            // uncomment below to test the property
            //modelInstance.completed shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

    }
}
