/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.nativebpm.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nativebpm.client.models.StartInstanceRequest

class StartInstanceRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StartInstanceRequest
        //val modelInstance = StartInstanceRequest()

        // to test the property `instanceId` - Optional user-generated UUID to enforce idempotency
        should("test instanceId") {
            // uncomment below to test the property
            //modelInstance.instanceId shouldBe ("TODO")
        }

        // to test the property `businessKey` - Business tracking keyword
        should("test businessKey") {
            // uncomment below to test the property
            //modelInstance.businessKey shouldBe ("TODO")
        }

        // to test the property `variables`
        should("test variables") {
            // uncomment below to test the property
            //modelInstance.variables shouldBe ("TODO")
        }

    }
}
