/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.nativebpm.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param instanceId 
 * @param nodeId 
 * @param nodeName 
 * @param nodeType 
 * @param action 
 * @param timestamp 
 * @param variables JSON encoded payload variables associated with this transition
 */


data class HistoryRecord (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "instance_id")
    val instanceId: java.util.UUID,

    @Json(name = "node_id")
    val nodeId: kotlin.String,

    @Json(name = "node_name")
    val nodeName: kotlin.String,

    @Json(name = "node_type")
    val nodeType: kotlin.String,

    @Json(name = "action")
    val action: kotlin.String,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* JSON encoded payload variables associated with this transition */
    @Json(name = "variables")
    val variables: kotlin.Any? = null

) {


}

