/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.nativebpm.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param host 
 * @param port 
 * @param username 
 * @param password 
 * @param from 
 * @param fromName 
 * @param useSsl 
 * @param maxHtmlSize 
 * @param maxAttachmentSize 
 * @param maxTotalAttachmentsSize 
 */


data class SMTPConfig (

    @Json(name = "host")
    val host: kotlin.String? = null,

    @Json(name = "port")
    val port: kotlin.Int? = null,

    @Json(name = "username")
    val username: kotlin.String? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "from")
    val from: kotlin.String? = null,

    @Json(name = "from_name")
    val fromName: kotlin.String? = null,

    @Json(name = "use_ssl")
    val useSsl: kotlin.Boolean? = null,

    @Json(name = "max_html_size")
    val maxHtmlSize: kotlin.Long? = null,

    @Json(name = "max_attachment_size")
    val maxAttachmentSize: kotlin.Long? = null,

    @Json(name = "max_total_attachments_size")
    val maxTotalAttachmentsSize: kotlin.Long? = null

) {


}

