/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.nativebpm.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param url 
 * @param events 
 * @param isActive 
 * @param enableAudit 
 * @param status 
 * @param createdAt 
 * @param secret 
 * @param processId 
 */


data class WebhookRecord (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "tenant_id")
    val tenantId: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "enable_audit")
    val enableAudit: kotlin.Boolean,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "secret")
    val secret: kotlin.String? = null,

    @Json(name = "process_id")
    val processId: kotlin.String? = null

) {


}

