/*
NativeBPM Engine REST API

REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the IncidentRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IncidentRecord{}

// IncidentRecord struct for IncidentRecord
type IncidentRecord struct {
	Id string `json:"id"`
	InstanceId string `json:"instance_id"`
	ActivityId string `json:"activity_id"`
	ErrorMessage string `json:"error_message"`
	StackTrace *string `json:"stack_trace,omitempty"`
	AttemptsMade int32 `json:"attempts_made"`
	Resolved bool `json:"resolved"`
	CreatedAt time.Time `json:"created_at"`
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
}

type _IncidentRecord IncidentRecord

// NewIncidentRecord instantiates a new IncidentRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentRecord(id string, instanceId string, activityId string, errorMessage string, attemptsMade int32, resolved bool, createdAt time.Time) *IncidentRecord {
	this := IncidentRecord{}
	this.Id = id
	this.InstanceId = instanceId
	this.ActivityId = activityId
	this.ErrorMessage = errorMessage
	this.AttemptsMade = attemptsMade
	this.Resolved = resolved
	this.CreatedAt = createdAt
	return &this
}

// NewIncidentRecordWithDefaults instantiates a new IncidentRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentRecordWithDefaults() *IncidentRecord {
	this := IncidentRecord{}
	return &this
}

// GetId returns the Id field value
func (o *IncidentRecord) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IncidentRecord) SetId(v string) {
	o.Id = v
}

// GetInstanceId returns the InstanceId field value
func (o *IncidentRecord) GetInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *IncidentRecord) SetInstanceId(v string) {
	o.InstanceId = v
}

// GetActivityId returns the ActivityId field value
func (o *IncidentRecord) GetActivityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetActivityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivityId, true
}

// SetActivityId sets field value
func (o *IncidentRecord) SetActivityId(v string) {
	o.ActivityId = v
}

// GetErrorMessage returns the ErrorMessage field value
func (o *IncidentRecord) GetErrorMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorMessage, true
}

// SetErrorMessage sets field value
func (o *IncidentRecord) SetErrorMessage(v string) {
	o.ErrorMessage = v
}

// GetStackTrace returns the StackTrace field value if set, zero value otherwise.
func (o *IncidentRecord) GetStackTrace() string {
	if o == nil || IsNil(o.StackTrace) {
		var ret string
		return ret
	}
	return *o.StackTrace
}

// GetStackTraceOk returns a tuple with the StackTrace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetStackTraceOk() (*string, bool) {
	if o == nil || IsNil(o.StackTrace) {
		return nil, false
	}
	return o.StackTrace, true
}

// HasStackTrace returns a boolean if a field has been set.
func (o *IncidentRecord) HasStackTrace() bool {
	if o != nil && !IsNil(o.StackTrace) {
		return true
	}

	return false
}

// SetStackTrace gets a reference to the given string and assigns it to the StackTrace field.
func (o *IncidentRecord) SetStackTrace(v string) {
	o.StackTrace = &v
}

// GetAttemptsMade returns the AttemptsMade field value
func (o *IncidentRecord) GetAttemptsMade() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptsMade
}

// GetAttemptsMadeOk returns a tuple with the AttemptsMade field value
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetAttemptsMadeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptsMade, true
}

// SetAttemptsMade sets field value
func (o *IncidentRecord) SetAttemptsMade(v int32) {
	o.AttemptsMade = v
}

// GetResolved returns the Resolved field value
func (o *IncidentRecord) GetResolved() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Resolved
}

// GetResolvedOk returns a tuple with the Resolved field value
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetResolvedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resolved, true
}

// SetResolved sets field value
func (o *IncidentRecord) SetResolved(v bool) {
	o.Resolved = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IncidentRecord) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IncidentRecord) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetResolvedAt returns the ResolvedAt field value if set, zero value otherwise.
func (o *IncidentRecord) GetResolvedAt() time.Time {
	if o == nil || IsNil(o.ResolvedAt) {
		var ret time.Time
		return ret
	}
	return *o.ResolvedAt
}

// GetResolvedAtOk returns a tuple with the ResolvedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentRecord) GetResolvedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolvedAt) {
		return nil, false
	}
	return o.ResolvedAt, true
}

// HasResolvedAt returns a boolean if a field has been set.
func (o *IncidentRecord) HasResolvedAt() bool {
	if o != nil && !IsNil(o.ResolvedAt) {
		return true
	}

	return false
}

// SetResolvedAt gets a reference to the given time.Time and assigns it to the ResolvedAt field.
func (o *IncidentRecord) SetResolvedAt(v time.Time) {
	o.ResolvedAt = &v
}

func (o IncidentRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IncidentRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["instance_id"] = o.InstanceId
	toSerialize["activity_id"] = o.ActivityId
	toSerialize["error_message"] = o.ErrorMessage
	if !IsNil(o.StackTrace) {
		toSerialize["stack_trace"] = o.StackTrace
	}
	toSerialize["attempts_made"] = o.AttemptsMade
	toSerialize["resolved"] = o.Resolved
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.ResolvedAt) {
		toSerialize["resolved_at"] = o.ResolvedAt
	}
	return toSerialize, nil
}

func (o *IncidentRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"instance_id",
		"activity_id",
		"error_message",
		"attempts_made",
		"resolved",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIncidentRecord := _IncidentRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIncidentRecord)

	if err != nil {
		return err
	}

	*o = IncidentRecord(varIncidentRecord)

	return err
}

type NullableIncidentRecord struct {
	value *IncidentRecord
	isSet bool
}

func (v NullableIncidentRecord) Get() *IncidentRecord {
	return v.value
}

func (v *NullableIncidentRecord) Set(val *IncidentRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentRecord(val *IncidentRecord) *NullableIncidentRecord {
	return &NullableIncidentRecord{value: val, isSet: true}
}

func (v NullableIncidentRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


