# coding: utf-8

"""
    NativeBPM Engine REST API

    REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TaskRecord(BaseModel):
    """
    TaskRecord
    """ # noqa: E501
    id: UUID
    instance_id: UUID
    activity_id: StrictStr
    name: StrictStr
    assignee: StrictStr
    candidate_groups: StrictStr
    status: StrictStr = Field(json_schema_extra={"examples": ["CREATED"]})
    due_date: Optional[datetime] = None
    input_schema: Optional[StrictStr] = Field(default=None, description="JSON schema definition of form widgets")
    created_at: datetime
    claimed_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    current_step: Optional[StrictInt] = None
    draft_variables: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "instance_id", "activity_id", "name", "assignee", "candidate_groups", "status", "due_date", "input_schema", "created_at", "claimed_at", "completed_at", "current_step", "draft_variables"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "instance_id": obj.get("instance_id"),
            "activity_id": obj.get("activity_id"),
            "name": obj.get("name"),
            "assignee": obj.get("assignee"),
            "candidate_groups": obj.get("candidate_groups"),
            "status": obj.get("status"),
            "due_date": obj.get("due_date"),
            "input_schema": obj.get("input_schema"),
            "created_at": obj.get("created_at"),
            "claimed_at": obj.get("claimed_at"),
            "completed_at": obj.get("completed_at"),
            "current_step": obj.get("current_step"),
            "draft_variables": obj.get("draft_variables")
        })
        return _obj


