/*
 * NativeBPM Engine REST API
 *
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DmnRuleAst {
    #[serde(rename = "inputs")]
    pub inputs: Vec<String>,
    #[serde(rename = "outputs")]
    pub outputs: Vec<String>,
}

impl DmnRuleAst {
    pub fn new(inputs: Vec<String>, outputs: Vec<String>) -> DmnRuleAst {
        DmnRuleAst {
            inputs,
            outputs,
        }
    }
}

