/*
 * NativeBPM Engine REST API
 * REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nativebpm.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IncidentRecord
 */
public class IncidentRecordTest {
    private final IncidentRecord model = new IncidentRecord();

    /**
     * Model tests for IncidentRecord
     */
    @Test
    public void testIncidentRecord() {
        // TODO: test IncidentRecord
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'instanceId'
     */
    @Test
    public void instanceIdTest() {
        // TODO: test instanceId
    }

    /**
     * Test the property 'activityId'
     */
    @Test
    public void activityIdTest() {
        // TODO: test activityId
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'stackTrace'
     */
    @Test
    public void stackTraceTest() {
        // TODO: test stackTrace
    }

    /**
     * Test the property 'attemptsMade'
     */
    @Test
    public void attemptsMadeTest() {
        // TODO: test attemptsMade
    }

    /**
     * Test the property 'resolved'
     */
    @Test
    public void resolvedTest() {
        // TODO: test resolved
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'resolvedAt'
     */
    @Test
    public void resolvedAtTest() {
        // TODO: test resolvedAt
    }

}
