/*
NativeBPM Engine REST API

REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nativebpm

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookRecord{}

// WebhookRecord struct for WebhookRecord
type WebhookRecord struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	Url string `json:"url"`
	Secret *string `json:"secret,omitempty"`
	Events []string `json:"events"`
	ProcessId *string `json:"process_id,omitempty"`
	IsActive bool `json:"is_active"`
	EnableAudit bool `json:"enable_audit"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type _WebhookRecord WebhookRecord

// NewWebhookRecord instantiates a new WebhookRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookRecord(id string, tenantId string, url string, events []string, isActive bool, enableAudit bool, status string, createdAt time.Time) *WebhookRecord {
	this := WebhookRecord{}
	this.Id = id
	this.TenantId = tenantId
	this.Url = url
	this.Events = events
	this.IsActive = isActive
	this.EnableAudit = enableAudit
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewWebhookRecordWithDefaults instantiates a new WebhookRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookRecordWithDefaults() *WebhookRecord {
	this := WebhookRecord{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookRecord) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookRecord) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *WebhookRecord) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *WebhookRecord) SetTenantId(v string) {
	o.TenantId = v
}

// GetUrl returns the Url field value
func (o *WebhookRecord) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookRecord) SetUrl(v string) {
	o.Url = v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *WebhookRecord) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *WebhookRecord) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *WebhookRecord) SetSecret(v string) {
	o.Secret = &v
}

// GetEvents returns the Events field value
func (o *WebhookRecord) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookRecord) SetEvents(v []string) {
	o.Events = v
}

// GetProcessId returns the ProcessId field value if set, zero value otherwise.
func (o *WebhookRecord) GetProcessId() string {
	if o == nil || IsNil(o.ProcessId) {
		var ret string
		return ret
	}
	return *o.ProcessId
}

// GetProcessIdOk returns a tuple with the ProcessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetProcessIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProcessId) {
		return nil, false
	}
	return o.ProcessId, true
}

// HasProcessId returns a boolean if a field has been set.
func (o *WebhookRecord) HasProcessId() bool {
	if o != nil && !IsNil(o.ProcessId) {
		return true
	}

	return false
}

// SetProcessId gets a reference to the given string and assigns it to the ProcessId field.
func (o *WebhookRecord) SetProcessId(v string) {
	o.ProcessId = &v
}

// GetIsActive returns the IsActive field value
func (o *WebhookRecord) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *WebhookRecord) SetIsActive(v bool) {
	o.IsActive = v
}

// GetEnableAudit returns the EnableAudit field value
func (o *WebhookRecord) GetEnableAudit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EnableAudit
}

// GetEnableAuditOk returns a tuple with the EnableAudit field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetEnableAuditOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnableAudit, true
}

// SetEnableAudit sets field value
func (o *WebhookRecord) SetEnableAudit(v bool) {
	o.EnableAudit = v
}

// GetStatus returns the Status field value
func (o *WebhookRecord) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookRecord) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookRecord) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookRecord) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookRecord) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o WebhookRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["url"] = o.Url
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	toSerialize["events"] = o.Events
	if !IsNil(o.ProcessId) {
		toSerialize["process_id"] = o.ProcessId
	}
	toSerialize["is_active"] = o.IsActive
	toSerialize["enable_audit"] = o.EnableAudit
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *WebhookRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"url",
		"events",
		"is_active",
		"enable_audit",
		"status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookRecord := _WebhookRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookRecord)

	if err != nil {
		return err
	}

	*o = WebhookRecord(varWebhookRecord)

	return err
}

type NullableWebhookRecord struct {
	value *WebhookRecord
	isSet bool
}

func (v NullableWebhookRecord) Get() *WebhookRecord {
	return v.value
}

func (v *NullableWebhookRecord) Set(val *WebhookRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookRecord(val *WebhookRecord) *NullableWebhookRecord {
	return &NullableWebhookRecord{value: val, isSet: true}
}

func (v NullableWebhookRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


