/*
NativeBPM Engine REST API

REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nativebpm

import (
	"encoding/json"
)

// checks if the OutVariable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutVariable{}

// OutVariable struct for OutVariable
type OutVariable struct {
	Source *string `json:"source,omitempty"`
	Target *string `json:"target,omitempty"`
	Variables *string `json:"variables,omitempty"`
}

// NewOutVariable instantiates a new OutVariable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutVariable() *OutVariable {
	this := OutVariable{}
	return &this
}

// NewOutVariableWithDefaults instantiates a new OutVariable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutVariableWithDefaults() *OutVariable {
	this := OutVariable{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *OutVariable) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutVariable) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *OutVariable) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *OutVariable) SetSource(v string) {
	o.Source = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *OutVariable) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutVariable) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *OutVariable) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *OutVariable) SetTarget(v string) {
	o.Target = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *OutVariable) GetVariables() string {
	if o == nil || IsNil(o.Variables) {
		var ret string
		return ret
	}
	return *o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutVariable) GetVariablesOk() (*string, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *OutVariable) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given string and assigns it to the Variables field.
func (o *OutVariable) SetVariables(v string) {
	o.Variables = &v
}

func (o OutVariable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutVariable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

type NullableOutVariable struct {
	value *OutVariable
	isSet bool
}

func (v NullableOutVariable) Get() *OutVariable {
	return v.value
}

func (v *NullableOutVariable) Set(val *OutVariable) {
	v.value = val
	v.isSet = true
}

func (v NullableOutVariable) IsSet() bool {
	return v.isSet
}

func (v *NullableOutVariable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutVariable(val *OutVariable) *NullableOutVariable {
	return &NullableOutVariable{value: val, isSet: true}
}

func (v NullableOutVariable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutVariable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


