/*
NativeBPM Engine REST API

REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nativebpm

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ProcessInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessInstance{}

// ProcessInstance struct for ProcessInstance
type ProcessInstance struct {
	Id string `json:"id"`
	ProcessId string `json:"process_id"`
	DefinitionHash string `json:"definition_hash"`
	BusinessKey string `json:"business_key"`
	// Base64/raw JSON encoded internal Wazero process engine state representation
	State string `json:"state"`
	Version int32 `json:"version"`
	Completed bool `json:"completed"`
	UpdatedAt time.Time `json:"updated_at"`
	TenantId string `json:"tenant_id"`
}

type _ProcessInstance ProcessInstance

// NewProcessInstance instantiates a new ProcessInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessInstance(id string, processId string, definitionHash string, businessKey string, state string, version int32, completed bool, updatedAt time.Time, tenantId string) *ProcessInstance {
	this := ProcessInstance{}
	this.Id = id
	this.ProcessId = processId
	this.DefinitionHash = definitionHash
	this.BusinessKey = businessKey
	this.State = state
	this.Version = version
	this.Completed = completed
	this.UpdatedAt = updatedAt
	this.TenantId = tenantId
	return &this
}

// NewProcessInstanceWithDefaults instantiates a new ProcessInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessInstanceWithDefaults() *ProcessInstance {
	this := ProcessInstance{}
	return &this
}

// GetId returns the Id field value
func (o *ProcessInstance) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProcessInstance) SetId(v string) {
	o.Id = v
}

// GetProcessId returns the ProcessId field value
func (o *ProcessInstance) GetProcessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessId
}

// GetProcessIdOk returns a tuple with the ProcessId field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetProcessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessId, true
}

// SetProcessId sets field value
func (o *ProcessInstance) SetProcessId(v string) {
	o.ProcessId = v
}

// GetDefinitionHash returns the DefinitionHash field value
func (o *ProcessInstance) GetDefinitionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefinitionHash
}

// GetDefinitionHashOk returns a tuple with the DefinitionHash field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetDefinitionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinitionHash, true
}

// SetDefinitionHash sets field value
func (o *ProcessInstance) SetDefinitionHash(v string) {
	o.DefinitionHash = v
}

// GetBusinessKey returns the BusinessKey field value
func (o *ProcessInstance) GetBusinessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessKey
}

// GetBusinessKeyOk returns a tuple with the BusinessKey field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetBusinessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessKey, true
}

// SetBusinessKey sets field value
func (o *ProcessInstance) SetBusinessKey(v string) {
	o.BusinessKey = v
}

// GetState returns the State field value
func (o *ProcessInstance) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ProcessInstance) SetState(v string) {
	o.State = v
}

// GetVersion returns the Version field value
func (o *ProcessInstance) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ProcessInstance) SetVersion(v int32) {
	o.Version = v
}

// GetCompleted returns the Completed field value
func (o *ProcessInstance) GetCompleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetCompletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Completed, true
}

// SetCompleted sets field value
func (o *ProcessInstance) SetCompleted(v bool) {
	o.Completed = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ProcessInstance) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ProcessInstance) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetTenantId returns the TenantId field value
func (o *ProcessInstance) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ProcessInstance) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ProcessInstance) SetTenantId(v string) {
	o.TenantId = v
}

func (o ProcessInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["process_id"] = o.ProcessId
	toSerialize["definition_hash"] = o.DefinitionHash
	toSerialize["business_key"] = o.BusinessKey
	toSerialize["state"] = o.State
	toSerialize["version"] = o.Version
	toSerialize["completed"] = o.Completed
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["tenant_id"] = o.TenantId
	return toSerialize, nil
}

func (o *ProcessInstance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"process_id",
		"definition_hash",
		"business_key",
		"state",
		"version",
		"completed",
		"updated_at",
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcessInstance := _ProcessInstance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProcessInstance)

	if err != nil {
		return err
	}

	*o = ProcessInstance(varProcessInstance)

	return err
}

type NullableProcessInstance struct {
	value *ProcessInstance
	isSet bool
}

func (v NullableProcessInstance) Get() *ProcessInstance {
	return v.value
}

func (v *NullableProcessInstance) Set(val *ProcessInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessInstance(val *ProcessInstance) *NullableProcessInstance {
	return &NullableProcessInstance{value: val, isSet: true}
}

func (v NullableProcessInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


