/*
NativeBPM Engine REST API

REST API for managing, executing, and monitoring workflows, human tasks, incidents, and outgoing webhooks inside the NativeBPM Cloud-Native engine.  ### Authentication Requests must include a session cookie or a Bearer API token: `Authorization: Bearer <API_TOKEN>` 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nativebpm

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExecuteProcessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteProcessResponse{}

// ExecuteProcessResponse struct for ExecuteProcessResponse
type ExecuteProcessResponse struct {
	// Process instance identifier
	InstanceId string `json:"instanceId"`
	// Process definition identifier
	DefinitionId string `json:"definitionId"`
	// Version number of the process definition
	Version int32 `json:"version"`
	// Indicates whether a new process definition version was deployed in this call
	IsNewVersionDeployed bool `json:"isNewVersionDeployed"`
	// Status of the created instance (e.g., ACTIVE, COMPLETED)
	Status string `json:"status"`
	// Current execution state variables and data
	State map[string]interface{} `json:"state,omitempty"`
	// Active tasks currently waiting for human intervention or external completion
	CurrentTasks []TaskRecord `json:"currentTasks,omitempty"`
}

type _ExecuteProcessResponse ExecuteProcessResponse

// NewExecuteProcessResponse instantiates a new ExecuteProcessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteProcessResponse(instanceId string, definitionId string, version int32, isNewVersionDeployed bool, status string) *ExecuteProcessResponse {
	this := ExecuteProcessResponse{}
	this.InstanceId = instanceId
	this.DefinitionId = definitionId
	this.Version = version
	this.IsNewVersionDeployed = isNewVersionDeployed
	this.Status = status
	return &this
}

// NewExecuteProcessResponseWithDefaults instantiates a new ExecuteProcessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteProcessResponseWithDefaults() *ExecuteProcessResponse {
	this := ExecuteProcessResponse{}
	return &this
}

// GetInstanceId returns the InstanceId field value
func (o *ExecuteProcessResponse) GetInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *ExecuteProcessResponse) GetInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *ExecuteProcessResponse) SetInstanceId(v string) {
	o.InstanceId = v
}

// GetDefinitionId returns the DefinitionId field value
func (o *ExecuteProcessResponse) GetDefinitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefinitionId
}

// GetDefinitionIdOk returns a tuple with the DefinitionId field value
// and a boolean to check if the value has been set.
func (o *ExecuteProcessResponse) GetDefinitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinitionId, true
}

// SetDefinitionId sets field value
func (o *ExecuteProcessResponse) SetDefinitionId(v string) {
	o.DefinitionId = v
}

// GetVersion returns the Version field value
func (o *ExecuteProcessResponse) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ExecuteProcessResponse) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ExecuteProcessResponse) SetVersion(v int32) {
	o.Version = v
}

// GetIsNewVersionDeployed returns the IsNewVersionDeployed field value
func (o *ExecuteProcessResponse) GetIsNewVersionDeployed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsNewVersionDeployed
}

// GetIsNewVersionDeployedOk returns a tuple with the IsNewVersionDeployed field value
// and a boolean to check if the value has been set.
func (o *ExecuteProcessResponse) GetIsNewVersionDeployedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsNewVersionDeployed, true
}

// SetIsNewVersionDeployed sets field value
func (o *ExecuteProcessResponse) SetIsNewVersionDeployed(v bool) {
	o.IsNewVersionDeployed = v
}

// GetStatus returns the Status field value
func (o *ExecuteProcessResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ExecuteProcessResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ExecuteProcessResponse) SetStatus(v string) {
	o.Status = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ExecuteProcessResponse) GetState() map[string]interface{} {
	if o == nil || IsNil(o.State) {
		var ret map[string]interface{}
		return ret
	}
	return o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecuteProcessResponse) GetStateOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.State) {
		return map[string]interface{}{}, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ExecuteProcessResponse) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given map[string]interface{} and assigns it to the State field.
func (o *ExecuteProcessResponse) SetState(v map[string]interface{}) {
	o.State = v
}

// GetCurrentTasks returns the CurrentTasks field value if set, zero value otherwise.
func (o *ExecuteProcessResponse) GetCurrentTasks() []TaskRecord {
	if o == nil || IsNil(o.CurrentTasks) {
		var ret []TaskRecord
		return ret
	}
	return o.CurrentTasks
}

// GetCurrentTasksOk returns a tuple with the CurrentTasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecuteProcessResponse) GetCurrentTasksOk() ([]TaskRecord, bool) {
	if o == nil || IsNil(o.CurrentTasks) {
		return nil, false
	}
	return o.CurrentTasks, true
}

// HasCurrentTasks returns a boolean if a field has been set.
func (o *ExecuteProcessResponse) HasCurrentTasks() bool {
	if o != nil && !IsNil(o.CurrentTasks) {
		return true
	}

	return false
}

// SetCurrentTasks gets a reference to the given []TaskRecord and assigns it to the CurrentTasks field.
func (o *ExecuteProcessResponse) SetCurrentTasks(v []TaskRecord) {
	o.CurrentTasks = v
}

func (o ExecuteProcessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteProcessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instanceId"] = o.InstanceId
	toSerialize["definitionId"] = o.DefinitionId
	toSerialize["version"] = o.Version
	toSerialize["isNewVersionDeployed"] = o.IsNewVersionDeployed
	toSerialize["status"] = o.Status
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.CurrentTasks) {
		toSerialize["currentTasks"] = o.CurrentTasks
	}
	return toSerialize, nil
}

func (o *ExecuteProcessResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instanceId",
		"definitionId",
		"version",
		"isNewVersionDeployed",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecuteProcessResponse := _ExecuteProcessResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExecuteProcessResponse)

	if err != nil {
		return err
	}

	*o = ExecuteProcessResponse(varExecuteProcessResponse)

	return err
}

type NullableExecuteProcessResponse struct {
	value *ExecuteProcessResponse
	isSet bool
}

func (v NullableExecuteProcessResponse) Get() *ExecuteProcessResponse {
	return v.value
}

func (v *NullableExecuteProcessResponse) Set(val *ExecuteProcessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteProcessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteProcessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteProcessResponse(val *ExecuteProcessResponse) *NullableExecuteProcessResponse {
	return &NullableExecuteProcessResponse{value: val, isSet: true}
}

func (v NullableExecuteProcessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteProcessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


